IT-s-CodingTest-Study/coding-test

- 유민/1주차/금/큐2.java
- 유민/1주차/금/프린터_큐.java
1. 큐 2
- Queue<Integer>를 활용하여 push, pop, size, empty, front, back 연산을 메서드로 분리해서 작성했습니다.
- BufferedReader와 StringBuilder를 사용해 속도를 높였습니다.
- push() 시에는 마지막으로 들어간 값을 따로 저장해 back() 명령 시 활용했습니다.
- 각 명령에 대해 if-else로 구분하여 해당 메서드를 호출하고 결과를 StringBuilder에 추가했습니다.
2. 프린터 큐
- 각 문서를 int[]{index, priority} 형태로 큐에 저장하고, 현재보다 더 높은 중요도의 문서가 큐에 남아 있는지 검사했습니다.
- 더 높은 중요도가 있다면 해당 문서를 다시 큐의 뒤로 보내고, 그렇지 않다면 순서를 뒤로 보냈습니다.
- 궁금한 문서의 인덱스와 비교하여 몇 번째로 인쇄되는지를 판단하였습니다.
- isHigherPriority() 메서드는 중요도 비교를 분리해 가독성을 높였습니다.
- 이 문제도 BufferedReader와 StringBuilder를 사용해 효율적으로 처리했습니다.
> [1주차] 이유민 - 금 큐2, 프린터 큐

- 재현/2주차/월/덱.java
- 재현/2주차/월/풍선터트리기.java
###문제 풀이
1. 덱
- 직접 Deque 클래스를 구현하여 덱의 모슨 연산을 배열 기반으로 처리하였습니다.
- MAX_SIZE를 지정하고 front, rear 포인터를 가운데부터 시작하게 하여 양방향 삽입과 삭제 연산을 O(1) 시간에 구현했습니다.
2. 풍선터트리기
- 덱의 양방향 이동을 활용하여 문제를 해결하였습니다.
- 앞에서 poll 하고 뒤에만 add를 하기 때문에 LinkedList 보다는 ArrayDeque를 이용했습니다.
- 풍선의 번호가 양수일 경우 pollFirst() 후 addLast()
- 풍선의 번호가 음수일 경우 pollLast() 후 addFirst()를 반복하며 문제를 해결하였습니다.
> [2주차] 김재현 - 월 덱, 풍선터트리기

- 경조/2주차/deque.java
- 경조/2주차/deque2.java
- 큐 때와 동일하게 deque를 이용하여 구현했습니다.
- 알고리즘 자체는 크게 어려운 것은 아닌데 백준 상으로 코드를 제출하면 메모리 초과가 떠서 해결하는데 시간을 썼습니다.
- "ArrayDeque은 LinkedList와 달리 다음 노드에 대한 참조를 유지할 필요가 없기 때문에 더 적은 메모리를 사용한다."를 보고 LinkedList에서 ArrayDeque로 바꿔 해결했습니다.
- 이동 값(move)이 양수면 move-1만큼 뒤에서 앞으로 풍선을 추가해주고 pollFirst를 하여 풍선을 확인하고, 
이동 값(move)이 음수면 move-1만큼 앞에서 뒤로 추가해주고 pollLast를 하여 풍선을 확인했습니다.
> [2주차] 정경조 - 월 덱, 풍선 터뜨리기

- 유민/2주차/월/덱.java
- 유민/2주차/월/풍선_터뜨리기.java
1. 덱
- Deque를 활용해서 push_front, push_back, pop_front, pop_back 같은 연산을 메서드로 분리해 처리했습니다.
- 문자열 명령어는 startsWith로 구분했고, 숫자는 split으로 추출해 사용했습니다.
- Deque는 ArrayDeque를 사용했고, 빈 덱일 경우 -1을 리턴하도록 예외 처리를 했습니다.
- StringBuilder로 출력값을 모아 마지막에 한 번에 출력했습니다.
2. 풍선 터뜨리기
- 풍선 번호랑 이동값을 갖는 Balloon 클래스를 만들어서 Deque에 저장했고, 처음 풍선부터 하나씩 터뜨리면서 남은 풍선을 회전시켰습니다.
- 양수면 오른쪽으로, 음수면 왼쪽으로 이동시켰고, 회전할 때는 pollFirst/addLast나 pollLast/addFirst를 이용했습니다.
- 풍선이 터질 때마다 그 번호를 출력에 추가했고, 마지막엔 StringBuilder로 결과 출력했습니다.
- 원형 구조를 직접 구현하지 않고 Deque 회전을 이용해 간단하게 처리했습니다.
> [2주차] 이유민 - 월 덱, 풍선 터뜨리기

- 지은/2주차/수/문자열_집합.java
- 지은/2주차/수/세로읽기.java
- 처음에는 ArrayList를 사용해서 풀이했습니다.
- 그런데 다른 사람들 풀이를 보니 대부분 HashSet을 사용하고 있었고, 성능 차이가 궁금해서 HashSet으로 변경해보았습니다.
- 직접 측정해보니 HashSet 사용 시  2800ms -> 384ms로 약 7배 이상 성능 차이가 났습니다.
- HashSet은 contains() 호출 시 평균 시간복잡도가 O(1)이기 때문에, '존재 여부 확인' 같은 상황에서 사용하면 아주 유리하다는 걸 이번에 알게 되었습니다.
---
- 5줄의 문자열을 세로로 읽어서 하나의 문자열로 이어붙이는 문제.
- 문자열 길이가 제각각이라서 단순하게 2중 for문으로 돌리면 인덱스 오류가 날 것 같았습니다.
- 그래서 먼저 각 문자열을 배열에 저장하고, 가장 긴 문자열의 길이를 기준으로 열을 순회하도록 했습니다.
- 세로로 읽는 방식은 col(열) → row(행) 순서로 반복하면서, 해당 인덱스에 문자가 존재할 때만 append하도록 조건을 넣었습니다.
> [2주차] 한지은 - 수 문자열 집합, 세로읽기

- 유민/3주차/수/기능개발.java
- 유민/3주차/수/스킬트리.java
1.	기능개발
- 각 기능이 완료되기까지 걸리는 일수를 Math.ceil()로 계산해 배열에 저장했습니다.
- 앞 기능이 끝나야 뒤 기능도 같이 배포될 수 있으므로, 기준일(deployDay)을 정해두고 그보다 늦게 끝나는 기능이 나오면 배포 묶음을 나눴습니다.
- 배포될 기능 개수를 리스트에 담아두고 마지막에 배열로 변환해 반환했습니다.
2.	스킬트리
- 각 스킬트리에서 주어진 스킬 순서(skill)에 포함된 문자만 골라서 StringBuilder에 따로 모았습니다.
- skill.startsWith()를 사용해 해당 스킬트리가 올바른 순서로 배워졌는지 확인했습니다.
- 필터링은 indexOf()로 처리했고, 따로 스택이나 큐 없이 문자열 처리만으로 구현했습니다.
> [3주차] 이유민 - 수 기능개발, 스킬트리

- 지은/5주차/수/게임 맵 최단거리.java
- 지은/5주차/수/여행 경로.java
- 최단 경로 탐색 문제로,BFS 사용
- 큐 사용하여 현재 위치에서 상하좌우 확장하여 탐색
- 방문한 좌표는 visited[][] 배열로 관리하고, 이동 가능한 경로는 maps[x][y] == 1 조건으로 판단
- 탐색이 끝난 뒤 도착지 좌표 (n-1, m-1)의 값이 여전히 1이라면 도달하지 못한 것으로 판단하고 -1을 반환
- 도달한 경우 해당 좌표에 누적된 값을 최단 거리로 반환
---
- 티켓을 사전순으로 정렬한 뒤 DFS로 모든 경로 탐색
- 경로는 List<String>에 누적 후 저장
- 사전순으로 가장 빠른 경로가 탐색되어 첫 번째 결과를 반환
- 개선할 점: 현재는 모든 경로를 탐색하지만, 불필요한 재귀를 줄이도록 최적화하면 더 좋을 것 같다.
- (예: 사전순 정렬이 되어 있다면, 첫 정답 이후 탐색을 종료하는 방식)
> [5주차] 한지은 - 수 게임 맵 최단거리, 여행 경로

- 유민/5주차/수/게임_맵_최단거리.java
- 유민/5주차/수/여행경로.java
dfs를 활용해 모든 티켓을 사용한 경로를 탐색하고 사전순으로 가장 빠른 경로를 선택하는 방식으로 풀이했습니다!
- 티켓 사용 여부는 boolean 배열로 추적했고,
- 경로는 문자열로 누적하여 완성된 경로만 리스트에 저장하면서
- 정렬 후 가장 앞선 경로를 정답으로 리턴했습니다.
최단 거리를 구해야 해서 bfs로 풀이했습니다.
- 큐에 현재 위치를 저장하고
- 거리 배열과 visited 배열을 별도로 유지하면서
- 상하좌우를 탐색해 도착지에 가장 먼저 도달했을 때의 거리를 반환하고
도착하지 못할 경우 -1을 반환하도록 구현했습니다.
> [5주차] 이유민 - 수 게임 맵 최단거리, 여행경로

- 재현/6주차/월/모음 사전.java
- 재현/6주차/월/전력망을 둘로 나누기.java
1. 모음사전
- DFS를 이용하여 모음을 이용하여 만들 수 있는 모든 문자열을 구하여 list에 추가
- list에서 구해야하는 문자열의 인덱스를 찾아서 출력
- StringBuilder를 이용하여 문자열을 더할때 연산 메모리 최적화
2. 전력망을 둘로 나누기
- List 배열을 이용하여 wire의 정보를 정리
- 전체 간선들 중 하나씩 지우면서 BFS를 진행하여 차가 가장 적은 결과를 업데이트
- BFS를 이용하여 전력망 안의 개수를 구함
---
- list에서 remove를 할때 매개변수에 따라 인덱스에 있는 값을 지울지 아니면 값에 해당하는 부분을 지울지에 대해 결정할 수 있다.
- `list[src].remove(Integer.valueOf(dst));` 라고 작성하는 경우 list[src]에서 dst라는 값을 삭제하라는 뜻이고
- `list[src].remove(dst);` 라고 작성하는 경우는 list[src]에서 dst 인덱스를 삭제하라는 의미로 
- remove 메서드는 오버로딩되어 있어 int를 넣으면 인덱스를 삭제하고, Object 객체를 넣으면 해당 값을 삭제한다.
> [6주차] 김재현 - 월 모음 사전, 전력망을 둘로 나누기

- 지은/6주차/월/모음사전.java
- 지은/6주차/월/전력망을 둘로 나누기.java
- DFS 사용하여 AEIOU로 만들 수 있는 길이 1~5의 모든 문자열 조합 생성
- 빈 문자열은 리스트에 포함되지 않도록 조건 처리
- 리스트에 저장된 문자를 indexOf로 위치 반환
- 가중치 계산 없이 완전탐색 기반으로 구현
---
- 각 간선을 하나씩 끊고, 두 전력망으로 나뉜 상태를 완전탐색
- 인접 리스트로 그래프 구성하고, DFS로 한 쪽 송전탑 개수(count)를 누적
- 간선 제거 후 복구를 반복하여 송전탑 개수 차이의 최소 차이값을 갱신
> [6주차] 한지은 - 월 모음사전, 전력망을 둘로 나누기

- 하나/6주차/월/모음사전.java
- 하나/6주차/월/전력망을둘로나누기.java
1. 모음 사전
- 각 자리마다 가중치를 두고 문자에 해당하는 단어 이전까지 만들어진 모든 조합 수를 계산  
- 마지막에 해당 단어 자체를 포함시키기 위해 단어의 길이만큼 더해 최종 순서를 구현
- 모음이 5개로 제한되고 사전 순서를 계산하는 구조가 5진법처럼 느껴져 응용해봤습니다!
--- 
2. 전력망을 둘로 나누기
- 모든 간선을 하나씩 제거하면서 그래프를 구성
- BFS로 한 쪽 트리의 노드 수를 계산
- 전체 노드 수에서 반대편 트리 노드 수를 구한 뒤 두 트리의 노드 수 차이의 최솟값을 구함
> [6주차] 김하나 - 월 모음사전, 전력망을 둘로 나누기

- 지은/6주차/수/메뉴 리뉴얼.java
- 모든 주문을 알파벳 순으로 정렬하여 조합 기준을 통일하고, 각 코스 길이에 대해 DFS로 가능한 메뉴 조합을 생성
- 생성한 조합은 map에 등장 횟수를 기록하고, 길이별로 2번 이상 등장한 조합 중 최빈 조합만 결과에 포함
- 최종 결과는 사전순으로 정렬하여 문자열 배열로 반환
- DFS 로직은 문자 포함 / 미포함 두 가지 선택을 통해 조합을 완전탐색하는 구조
> [6주차] 한지은 - 수 메뉴 리뉴얼

- 아빈/6주차/수/메뉴리뉴얼.java
- 메뉴 리뉴얼
- 해당 문제는 주문한 단품메뉴 조합에서 가장 많은 주문을 받은 조합을 뽑아내서 출력해내는 문제였습니다.
- 같은 조합으로 판단을 위해서 각 주문들을 정렬하고 dfs를 통해 course를 통해 주어진 길이마다 만들 수 있는 조합을 만들어주었습니다.
- 탐색이 끝나고 각 코스의 길이마다 최대로 등장하는 조합 횟수를 구한 후 2번 이상 등장한 조합 중 가장 많이 등장한 조합을 result_list에 추가하여 문제를 해결할 수 있었습니다.
> [6주차] 조아빈 - 수 메뉴 리뉴얼

- 유민/6주차/수/메뉴_리뉴얼.java
- 주문 문자열을 정렬한 뒤, dfs로 코스 길이별 가능한 조합을 모두 구했습니다.
- 각 조합은 Map에 등장 횟수를 넣어서 중복 체크했습니다.
- 2번 이상 등장한 조합 중 가장 많이 등장한 것만 골라서 결과에 넣었습니다.
- 조합 생성 후 카운팅하고 최대 빈도를 구해서 문제를 해결했습니다.
> [6주차] 이유민 - 수 메뉴 리뉴얼

- 유민/6주차/금/불량_사용자.java
- dfs 백트래킹으로 모든 경우의 수를 탐색했습니다.
- 각 불량 아이디에 대해 user_id와 매칭 가능한지를 isMatch로 확인하고, 중복된 조합은 Set을 사용해 걸러냈습니다.
- 조합의 순서가 상관없도록 정렬 후 문자열로 저장했습니다.
> [6주차] 이유민 - 금 불량 사용자

- 혁/6주차/금/불량_사용자.java
- `banned_id`는 `*` 와일드카드를 포함한 문자열입니다.
- `*`는 임의의 문자 하나와 매칭됩니다.
- `banned_id`와 매칭되는 `user_id`는 **길이도 동일해야 함**
- 순서는 다르더라도 동일한 사용자 조합은 하나로 취급
- 가능한 모든 사용자 조합의 경우의 수를 구해야 함
- 각 `banned_id`마다 정규식으로 바꿔서 대응되는 `user_id` 목록을 생성 해서 풀이
```java
String regex = banned.replace("*", ".");
> [6주차] 장혁 - 금 불량 사용자

- 경조/8주차/수/입국심사.java
- 처음에 이걸 시간복잡도를 따지면 완전탐색으로는 절대 못 푸는 문제여서 이진탐색(이분탐색)으로 어떻게 풀어야 하나 싶었습니다.
- 최저 시간(0) ~ 최대 시간(제일 느린 탐색대 * 인원수)을 이분 탐색하는 문제입니다.
- 만약 `mid`로 구한 시간을 각각의 탐색대에서 걸리는 시간으로 나눠 `sum` 값에 저장합니다.
- `sum` 값이 주어진 `n`보다 크거나 같으면 더 작은 시간으로도 완료할 수 있는지 반복합니다.
> [8주차] 정경조 - 수 입국심사

- 혁/8주차/수/입국심사.java
- **최소 시간**: `1`
- **최대 시간**: 가장 느린 심사관이 `n`명을 전부 처리하는 경우  
- `mid` 시간에 심사 가능한 사람 수를 계산
- 그 수가 `n`명 이상이면  
→ 시간 줄이기 (`max = center - 1`)
- 부족하면  
→ 시간 늘리기 (`min = center + 1`)
- 가능한 시간 중 최솟값을 `answer`에 저장
- `center` 시간 동안 각 심사관이 처리 가능한 인원  
→ `center / time`
- 모든 심사관의 처리 인원을 합산
- 모든 사람이 심사를 받는 데 필요한 **최소 시간**  
→ `answer`를 반환
> [8주차] 장혁 - 수 입국심사

- 재현/10주차/월/멀리 뛰기.java
1. 멀리 뛰기
- 가능한 횟수를 저장해주기 위한 dp 배열 생성
- 1칸과 2칸의 경우에는 규칙이 없기 때문에 1과 2를 대입
- 3칸 이상부터는 전 칸 + 전전 칸의 합의 횟수만큼 경우의 수가 생김 
- `n 번칸을 가야할 경우 n-1번칸에서 1칸 이동, n-2번칸에서 2칸 이동`
- 계속 더해주면 오버플로우가 발생하므로 횟수를 구할때 마다 1234567로 나눈 나머지를 저장
- `dp[i] = (dp[i - 1] + dp[i -2]) % 1234567`
- n까지 반복하며 dp[n]을 반환
> [10주차] 김재현 - 월 멀리 뛰기

- 경조/10주차/월/멀리뛰기.java
- 초반에 피보나치 수열을 생각하고 재귀로 구현했다가 시간초과가 났습니다.
- answer 배열 크기를 `n+1`로 구현한 이유는 n이 3이면 answer[3]에 저장을 해주기 위해서입니다.
- 기하급수적으로 늘어나기 때문에 계속 더하게 된다면 오버플로우가 날 수 있습니다. 
- 따라서 `%1234567`를 해주면서 answer에 저장해줘야 합니다.
> [10주차] 정경조 - 월 멀리 뛰기

- 경조/11주차/수/사칙연산.java
- 입력 배열 `arr`에서 숫자(`nums`)와 연산자(`oper`)를 각각 분리합니다.
- `dpMax[i][j]`, `dpMin[i][j]`는 `nums[i] ~ nums[j]` 범위의 부분 수식에서 만들 수 있는 최대/최소값을 의미합니다.
- `+` 연산은 큰 값끼리 더하는 게 최대가 되지만, `-` 연산은 큰 값 - 작은 값이 최대가 될 수 있으므로 최소값도 함께 관리해야 합니다.
- 점화식은 연산자 위치 `k`를 기준으로 수식을 좌우로 분할하고, 가능한 네 가지 조합
(`최대-최대`, `최대-최소`, `최소-최대`, `최소-최소`)의 결과를 계산하여 `dpMax[i][j]`와 `dpMin[i][j]`를 갱신합니다.
- 최종 정답은 전체 수식 범위인 `dpMax[0][N-1]`에 저장됩니다. (N은 nums의 길이)
> [11주차] 정경조 - 수 사칙연산

- 경조/13주차/월/방문길이.java
- 경조/13주차/월/숫자게임.java
- `그리디 알고리즘`을 적용하여 풀었습니다.
- `A`, `B`를 정렬해주었습니다.
- `idxA`, `idxB`를 정의하였습니다.
- `A[idxA]` < `B[idxB]`라면 `idxA`, `idxB`, `answer`를 모두 증가
- 아니라면 `idxB`만 증가해서 다시 비교합니다.
---
- 좌표평면 문제라 초반에 visited를 방문하는 방향까지 체크하기 위해 3차원 배열로 선언하긴 했지만 `[10][10][4]`로 선언했습니다.
- 하지만 좌표평면 상으로 -5 ~ 5까지는 총 11개의 숫자가 있기 때문에 `[11][11][4]`로 선언해줘야 합니다.
- `check` 함수: 다음 방문할 좌표`(nx, ny)`가 유효한지
- `d`: 방향`(좌: 0, 우: 1, 상: 2, 하: 3)`
- 현재 방향`(d)`으로 방문할 좌표`(nx, ny)`를 방문하지 않았다면 `visited[nx][ny][d]` 방문 처리
- `opposite`: `d`와 반대 방향 -> `(d % 2) == 0 ? d + 1 : d - 1`
- 방문할 좌표`(nx, ny)`에서 기존 방향`(x, y)` 방향으로도 `vistied[x][y][opposite]` 방문 처리
> [13주차] 정경조 - 월 숫자 게임, 방문 길이

- 유민/13주차/월/방문길이.java
- 유민/13주차/월/숫자게임.java
- A와 B 배열을 오름차순 정렬하여, B가 A보다 큰 값을 매칭할 수 있도록 구성
- 두 인덱스를 비교해 A의 각 원소보다 큰 B의 원소가 나오면 카운트 증가
- 좌표 이동 명령(dirs)에 따라 U/D/R/L 방향으로 이동하면서 방문 경로를 기록
- 경로는 방향성을 제거하기 위해 path와 reverse를 모두 저장하고, 최종적으로 절반 개수를 반환
> [13주차] 이유민 - 월 숫자 게임, 방문 길이

- 지은/13주차/수/광물캐기.java
- 지은/13주차/수/택배상자.java
- order 배열을 기준으로 트럭에 실을 수 있는 최대 상자 수를 계산하는 문제
- 벨트에서 1번부터 상자가 나오므로, box를 1부터 order 길이까지 증가시키며 반복
- 현재 상자 번호가 order[targetBox]와 같으면 트럭에 싣기
- 그렇지 않다면 스택에 push (보조 컨테이너에 보관)
- stack 맨 위가 order[targetBox]와 같으면 꺼내서 싣기
- 주어진 picks 배열을 사용하여 광물을 캘 때, 최소 피로도가 되도록 곡괭이 사용 순서를 정하는 문제
- 한 곡괭이는 최대 5개 광물을 캘 수 있으므로, (곡괭이 총 합) * 5 를 넘지 않도록 함
- 곡괭이 사용 순서를 고정시키지 않고 모든 가능한 조합을 탐색해야 함
- DFS 사용하여 사용할 곡괭이를 하나 선택하고 해당 곡괭이로 5개 광물을 캐며 피로도 누적
- 이후 남은 곡괭이로 다음 5개 광물을 캐는 방식으로 재귀 호출하며 모든 곡괭이 사용 순서 조합을 탐색
> [13주차] 한지은 - 수 택배 상자, 광물 캐기
