IT-s-CodingTest-Study/coding-test

재현/1주차/금/큐2.java, 재현/1주차/금/프린터_큐.java, 재현/1주차/수/스택.java, 재현/1주차/수/스택_수열.java
- 스택 : 배열을 이용해서 직접 Stack 자료 구조를 구현하여 문제 풀이 
- 스택 수열 : Stack 자료 구조를 이용하여 push하여 오름차순으로 스택을 채우고 필요할 때 pop 수행
=> [1주차] 김재현 - 수 스택, 스택 수열

아빈/1주차/수/스택.java, 아빈/1주차/수/스택수열.java
- 스택(10828) : 스택 자료구를 활용하여 풀이 하는 방법도 있었지만,  배열을 사용하여 스택의 기본 메소드를 비슷하게 직접 구현해볼 수 있을 것  같아 한 번 해보았습니다.  스택의 top을 코드 상의 length로 활용하여 문제를 해결할 수 있었습니다.
- 스택수열(1874) : 항상 백준 문제나 코테 문제를 볼때마다 한국말이 참 어려운 것 같습니다. 이 또한 이전 문제와 마찬가지로 스택이 아닌 배열을 활용하여 해결할 수 있었습니다. 조건식을 제대로 걸어주지 않아 에러가 몇 번 발생 했지만, 스택(코드 상으로는 배열)의 마지막 요소를 꺼내서 입력한 자연수의 값을 비교하는 경우를 좀 더 생각하여 해결할 수 있었습니다.
=> [1주차] 조아빈 - 수 스택, 스택수열

혁/1주차/수/스택.java, 혁/1주차/수/스택_수열.java
수 스택 : ArrayList을 이용해서 스택 자료 구조를 구현하여 문제 해결
스택 수열 : JAVA의 스택 인터페이스(push, pop ,peek,)과 ArrayList를 이용해서 수열 문제 해결
=> [1주차] 장혁 - 수 스택, 스택 수열

경조/1주차/수/stack.java, 경조/1주차/수/stack_sequence.java
- 스택(10828번): ArrayList를 이용하여 스택을 구현했습니다. switch-case 문을 통해 명령을 수행하도록 구현했습니다.
- 스택 수열(1874번): 문제를 계속 읽고 이해조차 되지 않아 유튜브, 인터넷에 검색해서 겨우 이해하고 구현했습니다. 그러다보니 코드를 더 간결하게 할 수 있을 것 같은데 너무 길게 구현된 것 아닌가 생각이 듭니다.
Stack 클래스를 사용해 구현했으며 StringBuffer를 이용해 push, pop 연산을 저장했습니다.
=> [1주차] 정경조 - 수 스택, 스택 수열

지은/1주차/금/큐2.java, 지은/1주차/금/프린터큐.java
- back 명령 처리를 위해 양뱡향 큐 Deque을 사용했습니다.
- 명령어는 공백(" ") 기준으로 분리하여여 처리했습니다.
- 사실 Queue로도 충분히 구현 가능할 것 같은데, 문제를 보고 처음 떠오른 자료구조가 Deque라서 사용했습니다.
---
- 문제에서 주어진 입출력 예시가 어떤 의미를 가지는지 처음에 이해되지 않아 어렵게 느껴졌습니다.  
- 인덱스와 중요도를 함께 저장하기 위해 큐를 사용했고, 중요도가 낮은 작업은 뒤로 보내는 방식으로 로직을 구성했습니다.  
- 선언해야 할 변수들이 많다 보니 변수명에 대한 고민이 컸고, 지금은 최대한 의미를 담아 명확하게 작성하려고 했습니다.  
- 앞으로는 어떻게 하면 더 깔끔하게 변수나 구조를 정리할 수 있을지도 고민해봐야 할 것 같습니다.
=> [1주차] 한지은 - 금 큐2, 프린터큐

경조/1주차/금/printer_queue.java, 경조/1주차/금/queue.java
- 순간 생각난 것이 Deque여서 Deque를 이용하여 해결했습니다.
- 명령어는 공백을 기준으로 분리했습니다.
- 문제는 이해했는데 어떻게 구현하지 생각이 들어 좀 오래 걸렸습니다.
- 큐2 문제와 다르게 읽어야 할 값이 많아 StringTokenizer를 사용했습니다.
- [문서 번호, 중요도] 같은 배열로 저장하게 큐를 구현했습니다.
=> [1주차] 정경조 - 금 큐2, 프린터 큐

혁/1주차/금/큐2.java, 혁/1주차/금/프린터_큐.java
1️⃣ 큐2
지난 과제에서 지적 받은 출력문제를 BufferedWriter를 사용해 메모리 효율 문제 해결
if-else 문이 아닌 case-switch문으로 간결하게 조건문 생성
arrayList와 자바의 queue 인터페이스를 사용해서 문제 해결
2️⃣ 스택 수열
I/O는 BufferedReader와 StringBuilder + BufferedWriter 사용
자바의 queue와 우선순위queue 인터페이스를 사용해서 해결
->원하는 문서가 나올때까지 poll하고 add 하며 문서 순서를 찾음.
=> [1주차] 장혁 - 금 큐2,프린터 큐

하나/1주차/금/큐2.java, 하나/1주차/금/프린터큐.java
1️⃣ 큐2
- 배열을 기반으로 한 Queue 클래스를 직접 구현.
- empty, size, front, back 등 큐의 기본 동작을 메서드로 구현
2️⃣ 프린터큐 
- 큐에 인덱스와 중요도를 함께 저장하는 Node 클래스 사용
- 현재 문서보다 더 높은 중요도를 가진 문서가 남아 있는지 확인 후 없다면 출력
현재 프린터큐 문제의 중요도 확인을 위해 큐 전체 순회하는 방법을 선택했는데, 
PriorityQueue를 사용하면 가장 높은 중요도를 바로 알 수 있어 코드를 줄일 수 있을 거라 생각해 시도해보았지만 
성공하지 못했습니다.
=> [1주차] 김하나- 금 큐2, 프린터큐 

아빈/1주차/금/큐2.java, 아빈/1주차/금/프린터큐.java
##문제 풀이
- 이전 스택 문제와 유사한 문제여서 큐에대한 기본 지식만 있다면 크게 어려운 문제는 아니었습니다. 
- 다른 분들 코드를 봤을때 일반 배열보다는 확실히 컬렉션 프레임워크를 사용하는 것이 편해보여 저도 사용해보았습니다. ArrayList를 사용하여 맨 앞의 요소를 제거 할 시 요소들을 한칸씩 앞으로 옮기는 과정이 있어 시간 초과 문제가 있었습니다. 
- 해당 과정이 필요없는 LinkedList를 활용하여 문제를 해결할 수 있었습니다.
- 이번에도 두 번째 문제를 이해하는 데에만 시간이 많이 걸렸습니다.
- 해당 문제는 맨 앞의 요소와 나머지 요소들의 중요도를 비교해서 더 높은 중요도를 가진 요소가 있을 시 맨 뒤로 옮기는 과정을 거치며 중요도가 가장 높은 요소를 빼내야 하는 문제였습니다.
- 최댓값을 비교하는 max라는 변수를 활용할 생각을 못해서 많이 헤맸던 문제였습니다..!
=> [1주차] 조아빈 - 금 큐2, 프린터 큐

혁/2주차/월/덱.java, 혁/2주차/월/풍선_터트리기.java
입출력 연산은 sb, br ,bw을 static으로 사용해서 메모리 효율을 극대화 했고,
switch-case 문으로 java deque 인터페이스를 사용해서 명령어 받고 출력 sb에 저장 후 bw로 출력했습니다.
---
입출력 연산은 sb, br ,bw을 static으로 사용해서 메모리 효율을 극대화 했고,
입력한 풍선의 이동 값으로 풍선을 차례대로 터뜨리고, 터진 풍선의 인덱스를 출력했습니다. 이동 방향에 따라 풍선을 재배치 하고 sb에 저장 후 bw로 출력했습니다.
=> [2주차]장혁 - 월 덱,풍선 터트리기

하나/2주차/월/덱.java, 하나/2주차/월/풍선터뜨리기.java
1️⃣ 덱
- 배열 기반으로 직접 Deque를 구현하여 기본 연산을 수행하는 매서드를 구현
- 배열의 중간 기준으로 앞뒤 삽입/삭제가 가능하도록 front와 rear인덱스를 조정하여 구현
- size()는 (rear - front)로 간단하게 계산할 수 있도록 처리
2️⃣ 풍선 터뜨리기
- Deque(LinkedList) 를 활용해 풍선을 [번호, 이동값] 형태로 저장하고 처리하도록 구현
- 풍선 제거는 pollFirst() 이동은 addLast(), addFirst()를 활용하여 방향성에 따라 큐 회전 구현
- 
배열로 구현할 수 있을 것 같았는데, 생각보다 터진 풍선을 건너뛰는 로직이 복잡해져 실패했고, 결국 Deque를 사용했습니다.
다 풀고 나니  처음부터 2차원 배열을 선언해 풍선 번호와 이동 값을 함께 저장했으면  배열 기반으로도 충분히 구현이 가능했을 것 같습니다. 다음에는 구조를 먼저 정리한 후 구현에 들어가는 습관을 들여야겠다고 느꼈습니다.
=> [2주차] 김하나 - 월 덱, 풍선 터뜨리기

아빈/2주차/월/덱.java, 아빈/2주차/월/풍선터뜨리기.java
- 덱의 기본 함수들을 연습해볼 수 있는 문제였습니다.
- 이전의 스택이나 큐 문제 기본 문제들과 크게 다를게 없어서 푸는데 어려움은 없었습니다.
- 이전에도 도전했다가 포기했던 문제였는데, 드디어 해답을 얻을 수 있어 좋았습니다.
- 움직여야 하는 수를 음수와 양수의 조건으로 나누어 풀어야 한다는 것까지는 알았으나, 인덱스를 이동해야 하는 것에 있어 큰 어려움을 느꼈습니다.
- 조건에 따라 지워야 하는 풍선을 가장 앞이나 뒤에 배치시켜 제거할 수 있도록 하였습니다.
=> [2주차] 조아빈 - 월 덱, 풍선 터뜨리기

하나/2주차/수/문자열집합.java, 하나/2주차/수/세로읽기.java
1️⃣ 문자열 집합
- 첫 번째 입력에서 n개의 문자열을 받아 배열에 저장
- 이후 m개의 문자열을 입력 받아 해당 문자열이 배열에 존재하는지 비교
- 존재하는 경우 count++를 통해 개수를 확인
2️⃣ 세로 읽기
- 5개의 단어를 입력 받아 배열에 저장
- 열 인덱스를 순회하면서 각 열에 대해 문자가 존재하면 출력 결과에 포함
- 문자가 존재하지 않다면 무시
=> [2주차]김하나 - 수 문자열_집합, 세로읽기

재현/2주차/수/문자열_집합.java, 재현/2주차/수/세로읽기.java
1. 문자열 집합
- 배열의 경우 찾는 시간이 O(n^2)이 걸리기 때문에 시간 최적화를 위해 Set을 이용하여 풀었습니다.
- HashSet의 경우 입력 O(1) 찾기 O(1)으로  시간적으로 더 효율적이였습니다.
3. 세로읽기
- String 배열 5개를 선언한 후 5개의 문자열 값 중 가장 긴 문자열의 길이를 max 변수에 저장하였습니다.
- max까지의 for문을 돌면서 br에 문자 추가하여 출력하였습니다.
=> [2주차] 김재현 - 수 문자열 집합, 세로읽기

하나/2주차/금/문자열내마음대로정렬하기.java, 하나/2주차/금/완주하지못한선수.java
1️⃣ 문자열 내 마음대로 정렬하기
- HashMap에 각 문자열과 n번째 문자를 매핑
-  Comparator를 이용하여 n번째 문자를 기준으로 정렬하고
- 동일할 경우 사전순으로 정렬  
2️⃣완주하지 못한 선수
- HashMap을 이용하여 참가자의 이름과 등장 횟수를 저장
- 완주자의 이름은 등장 횟수를 -1 하여 처리
- 마지막에 HashMap에서 value가 0이 아닌 key를 찾아 리턴
=> [2주차] 김하나 - 금 문자열 내 마음대로 정렬하기, 완주하지 못한 선수

아빈/2주차/금/문자열내마음대로정렬하기.java, 아빈/2주차/금/완주하지못한선수.java
- 문자열 내 마음대로 정렬하기
- n번째 문자를 비교하여 배열 요소들을 정렬해야 하는 문제였습니다.
- 만약 n번째 문자가 같은 경우 사전적 비교를 하여 정렬을 해야합니다.
- 해당 부분에서 정확히 알지 못해서 공부할 수 있었습니다.
- List에 비교할 문자 + 문자열을 합친 새 문자열로 삽입 한 후 Collections.sort(list)을 통해 만약 첫 글자가 같으면 사전적비교를 한 후 정렬을 하여 해결할 수 있었습니다.
- 비교할 문자를 앞에 둔 이유는 문자열의 첫 글자부터 비교를 하기 때문입니다.
- 완주하지 못한 선수
- 이전에 HashMap을 활용하여 문제를 푼 기억이 있어서 그런지 생각보다 쉽게 풀었습니다. 
- 참가자 이름을 키로 하여 등장 횟수를 저장하고, 완주한 선수의 이름은 그만큼 감소시키는 방식으로 구현했습니다.
- 최종적으로 값이 남은 키가 완주하지 못하는 선수가 되도록 하여 해결하였습니다
=> [2주차] 조아빈 - 금 문자열 내 마음대로 정렬하기, 완주하지 못한 선수

경조/2주차/금/StringSort.java, 경조/2주차/금/marathon.java, 경조/2주차/금/marathon2.java
- Arrays.sort를 사용해서 구현했습니다.
- 문자열 2개에서 비교하고자 하는 n번째 요소의 문자를 각각 따와 비교합니다.
- 같을 시 문자열을 compareTo 메소드를 이용하여 비교합니다.
- 같지 않을 시 n번째 요소의 알파벳을 compare 메소드를 이용하여 정렬합니다.
- 방문 여부(완주 여부)를 확인하는 참가자 명단 크기의 complete 배열을 사용했습니다.
- 이중 반복문을 통해 조회를 했는데 처음 루프에서 참여자 명단만큼 반복을 하면 동명이인을 구별할 수 없어 처음 루프에서 완주자 명단만큼 반복했습니다.
- 완주자 명단에 이름이 참가자 명단에서 complete 값이 false고 이름이 같다면 complete 배열의 값을 true 값으로 바꿔주고 반복문을 탈출합니다.
- 테스트 케이스는 통과했지만 효율성 테스트는 떨어져서 수정이 필요합니다.
- 해시 문제인 줄 모르고 해시를 사용 안 했었습니다.
- 해시 사용해서 해결 완료했습니다.
=> [2주차] 정경조 - 금 문자열 내 마음대로 정렬하기, 완주하지 못한 선수

혁/2주차/금/문자열_내_마음대로_정렬하기.java, 혁/2주차/금/완주하지_못한_선수.java
-  Array.sort 와 compare 라이브러리 함수 사용해서 해결
- 테스트 케이스 추가해서 한번 더 검증 ### 완주 하지 못한 선수
- HashMap을 사용하여 map함수인 put , get을 활용하여 해결
- 테스트 케이스 추가해서 한번 더 검증
=> [2주차] 장혁 - 금 문자열 내 마음대로 정렬하기, 완주하지 못한 선수

지은/2주차/금/문자열 내 마음대로 정렬하기.java, 지은/2주차/금/완주하지 못한 선수.java
- 문자열 배열을 n번째 문자 기준으로 정렬하는 문제입니다.
- n번째 문자를 각 단어의 맨 앞에 붙이고, Arrays.sort()로 정렬한 뒤, 다시 복구하는 방식으로 구현했습니다.
---
- Arrays.sort()를 사용하여 참가자 배열과 완주자 배열을 오름차순으로 정렬했습니다.
- 정렬된 두 배열을 앞에서부터 비교하여 처음으로 다른 값이 나오는 시점의 참가자를 완주하지 못한 사람으로 판단했습니다.
- 예를 들어, 두 배열이 정렬된 상태에서 `participant[i]`와 `completion[i]`가 다르면 그 참가자가 완주하지 못한 사람입니다.
- 만약 끝까지 모두 같다면, 참가자 배열의 마지막 요소가 완주하지 못한 사람입니다.
=> [2주차] 한지은 - 금 문자열 내마음대로 정렬하기, 완주하지 못한 선수

재현/3주차/월/문자열 압축.java, 재현/3주차/월/특별한 이차원 배열 2.java
1. 특별한 이차원 배열2
- 이중 반복문을 통하여 arr[i][j]와 arr[i][j]가 서로 같은지 다른지 확인하였습니다.
- arr[x][x]를 기준으로 위쪽 또는 아래쪽 부분 중 한 부분만 확인해도 정답을 구할 수 있기때문에 for문의 인덱스를
j = i부터로 시작하여 구현하였습니다.
3. 문자열 압축
- 주어진 문자열을 token 길이 단위로 잘라 큐에 넣고 동일한 문자열이 연속되면 개수를 세어 sb에 추가하여 구현하였습니다.
- 정해진 token에 대해 압축 문자열이 완성되었으면 만들 수 있는 짧은 압축 문자열에 대해 비교하며 업데이트 하였습니다.
=> [3주차] 김재현 - 월 특별한 이차원 배열2, 문자열 압축

경조/3주차/월/문자열압축.java, 경조/3주차/월/특별한이차원배열2.java
- 배열길이가 nxn으로 행과 열 둘 다 같아 arr.length를 이용해 이중반복문으로 해결했습니다.
- 알고리즘을 이해한 뒤에 푸는데 어려움을 많이 느꼈습니다.
- 문자열을 자르는 단위 n을 1부터 문자열 길이/2까지 반복을 해주는 첫번째 for문
- 문자열 단위마다 count=1, StringBuffer, 처음 자르는 문자열 str을 선언했습니다.
- 그 다음 for문은 n번째 요소부터 확인을 하면 되므로 n부터 값은 n씩 늘려가며 문자열길이-n까지 반복을 해주었습니다.
=> [3주차] 정경조 - 월 특별한 이차원 배열2, 문자열 압축

아빈/3주차/월/문자열압축.java, 아빈/3주차/월/특별한이차원배열2.java
- 특별한 이차원 배열2
- 2중 반복문 안에서 열과 행을이 바뀌었을때 같은지 비교하기만 하면 되서 빠르게 해결할 수 있던 문제였습니다.
- 문자열 압축
- 1단계 올라갔다고 이렇게 난이도 차이가 있을 줄은 몰랐습니다..
- 인덱스를 증가시키며 남은 문자열을 붙여야 하는 과정이 잘 안됐던 것 같습니다.
- 나누어야 하는 문자열을 증가 시키기 전 압축된 문자열과 이전의 문자열의 길이를 비교하며 문제를 해결할 수 있었습니다
=> [3주차] 조아빈- 월 특별한 이차원 배열2, 문자열 압축

하나/3주차/수/기능개발.java, 하나/3주차/수/스킬트리.java, 하나/3주차/월/문자열압축.java, 하나/3주차/월/특별한이차원배열2.java
1️⃣   특별한 이차원 배열2  
- 이중 for문을 사용하여 모든 원소를 비교
- 하나라도 다르면 0 리턴 (대칭 아님)
- 나머지 경우는 1 리턴 
2️⃣ 문자열 압축 
-  `for (int step = 1; step <= s.length()/2; step++)`로 가능한 단위 반복
- `substring`으로 문자열 잘라서 비교
-  만약 비교할 문자열이 이전과 같다면 (aa)
-  count 증가, 다르다면 압축된 문자열을 새로 저장 `(count > 1 ? count + prev : prev)`
-  압축된 문자열이 원래 문자열의 길이 보다 작다면 길이를 갱신 
-  최종 문자열 길이를 반환
=> [3주차] 김하나 - 월 특별한 이차원 배열2, 문자열 압축

혁/3주차/월/문자열_압축.java, 혁/3주차/월/특별한_이차원_배열2.java
- 특별한 이차원 배열2 : 주어진 이차원 배열이 대칭 행렬인지 확인하기 위해 배열의 모든 원소 쌍 arr[i][j]와 arr[j][i]를 비교하며, 만약 두 원소가 다르면 0을 반환하여 대칭이 아님을 표시하고, 모든 원소가 일치하면 1을 반환하여 대칭임을 나타냅니다. 
- 문자열 압축 : 각 단위 길이에 대해 문자열을 반복적으로 비교하고, 반복되는 부분은 카운트하여 압축된 문자열을 생성합니다. 마지막에는  가장 짧은 압축 문자열의 길이를 반환합니다ㅏ.
=> [3주차]장혁- 월 특별한 이차원 배열2, 문자열 압축

유민/3주차/월/문자열_압축.java, 유민/3주차/월/특별한_2차원_배열2.java
1. 문자열 압축
- 문자열을 일정 단위로 잘라가며 반복되는 패턴을 압축하는 방식으로 구현했습니다.
- 단위 길이는 1부터 문자열 길이의 절반까지 시도했고, 매번 압축한 결과를 StringBuilder에 저장했습니다.
- 이전 문자열과 현재 문자열이 같으면 count를 올리고, 다르면 압축 문자열에 count와 이전 문자열을 추가했습니다.
- 마지막에 남은 문자열 처리도 따로 해줬고, 매 단위마다 압축한 길이 중 최솟값을 갱신해 최종 결과로 리턴했습니다.
2. 특별한 이차원 배열 2
- 이차원 배열이 대칭인지 확인하는 문제로, arr[i][j] == arr[j][i]를 모든 i, j에 대해 확인했습니다.
- 이중 반복문을 돌면서 한 번이라도 조건을 만족하지 않으면 바로 0을 리턴하고, 끝까지 통과하면 1을 리턴했습니다.
=> [3주차] 이유민 - 월 특별한 이차원 배열2, 문자열 압축

재현/3주차/수/기능개발.java, 재현/3주차/수/스킬트리.java
1. 기능 개발
- 각 기능의 배포까지 필요한 날짜를 계산하여 큐에 저장
- 큐에서 하나씩 빼며 앞 기능이 완료될때 뒷 기능도 배포가 가능하면 개수를 세어서 count 변수에 저장
- 각 배포 시점마다 몇 개의 기능이 배포되는지 리스트에 저장한 후 배열로 변환하여 출력
2. 스킬 트리
- 스킬트리에서 skill 문자열에 포함된 스킬만 순서대로 저장
- 저장된 스킬 순서가 skill의 앞 순서와 일치하는지 확인
- 조건을 만족하는 스킬트리의 개수를 세어 출력
=> [3주차] 김재현 - 수 기능개발, 스킬트리

경조/2주차/금/StringSort.java, 경조/2주차/금/marathon.java, 경조/3주차/수/기능개발.java, 경조/3주차/수/스킬트리.java
- day 배열에는 진도율을 속도로 나누었을 때 나머지가 0이 아니라면 남은 일수를 계산하여 저장했습니다.
- day 배열 크기만큼 반복하면서 현재 작업(day[0])의 남은 일수보다 작으면 count 값을 증가, 아니라면 현재 작업을 변경해주고 count 값을 초기화 해줬습니다.
- 배울 스킬의 문자를 charAt 메소드를 통해 하나 씩 분리했습니다.
- 스킬에서 분리한 문자의 index가 조회가 되는지 확인했습니다.
- 조회가 되었는데 스킬의 현재 인덱스에 해당하는 문자랑 같이 않다면 index 값을 -1로 설정 같다면 index 값을 증가시켜줬습니다.
- 스킬트리 하나를 돌고 난 후에는 index 값이 -1이 아니라면 count 값을 증가 시켜줬습니다.
=> [3주차] 정경조 - 수 기능개발, 스킬트리

지은/3주차/수/기능개발.java, 지은/3주차/수/스킬트리.java
- 각 기능 별 완료까지 필요한 날짜 계산
- 앞에 있는 기능이 완료되어야만 뒤에 있는 기능도 배포 가능하므로 큐 사용
- 큐 사용하여 기능을 배포 단위로 묶어 처리
---
- 선행 스킬 순서 유효성 검사하는 문제
- skill 문자열과 각 스킬 트리에 대해 문자를 하나씩 비교하며 선행 순서 체크
- 선행 스킬을 배우지 않은 상태에서 뒤 순서 스킬이 나오면 불가능한 스킬트리로 판단
- 유효한 스킬 트리일 경우 카운트 증가시켜 출력
=> [3주차] 한지은 - 수 기능개발, 스킬트리

아빈/3주차/수/기능개발.java, 아빈/3주차/수/스킬트리.java
- 기능개발
- 해당 문제는 작업속도가 서로다른 기능개발에 따라 함께 끝낼 수 있는 작업의 개수를 구분하여 계산 후 출력해내는 문제였습니다.
- 남은 진행률과 작업속도로 완료까지 남은 일수를 계산하고 앞의 남은 일수가 뒤의 남은 일수보다 크다면 count를 증가시키는 방식으로 해결할 수 있었습니다.
- 스킬트리
- 해당 문제는 다른 스킬과 관계없이 선행 스킬들이 순서에 맞게 되어 있는지 판별하여 해결하는 문제입니다
- 스킬트리에서 선행스킬의 스킬들을 빼내고 해당 스킬들이 알맞게 정렬되어 있다면 answer을 1씩 증가시키며 해결해나갈 수 있었습니다.
- 스킬트리가 제대로된 순서인지 비교하기 위해 equals를 처음에 사용했는데, 주어진 선행스킬 순서 중 순서만 지키면 모든 스킬을 배우지 않아도 되는 것이라 틀린 경우가 나오게 되었습니다.
- startsWith를 사용하여 위의 문제를 해결할 수 있었ㅅ브니다.
=> [3주차] 조아빈 - 수 기능개발, 스킬트리

혁/3주차/금/베스트앨범.java, 혁/3주차/금/키패드_누르기.java, 혁/3주차/수/기능개발.java, 혁/3주차/수/스킬트리.java
- 기능개발 : 주어진 코드는 progresses와 speeds 배열을 받아 각 기능별 남은 개발 일수를 계산해 days 배열에 저장하고, days를 순회하며 앞선 기능의 배포일(maxDay)보다 작거나 같으면 같은 배포 그룹으로 묶고 크면 새로운 배포 그룹을 생성합니다. 각 배포 그룹별 기능 개수를 리스트에 저장한 뒤, 이를 배열로 변환해 반환합니다.
- 스킬트리 : 선행 스킬 문자열 s와 스킬트리 배열 t를 입력받아, 각 스킬트리에서 s에 포함된 문자만 순서대로 추출(filtered)하고, 이 filtered가 s의 접두사(startsWith)인지 확인했습니다. 접두사일 경우 조건을 만족하는 스킬트리로 판단하여 카운트(count)하고, 모든 스킬트리를 검사한 후 가능한 스킬트리 개수를 반환했습니다.
=> [3주차]장혁 - 수 기능개발, 스킬트리

재현/3주차/금/베스트앨범.java, 재현/3주차/금/［카카오 인턴］ 키패드 누르기.java
1. 베스트 앨범
- genre, play, index를 갖는 Music 객체를 생성하여 입력값을 관리하였습니다.
- 모든 노래를 재생 수 기준으로 정렬하였습니다.
- map을 이용하여 장르별 재생수를 저장하였고 genreList에 map의 keySet을 저장하여 정렬하였습니다.
- 이후 정렬된 노래 목록을 순회하며 해당 장르의 노래를 2개씩 선택하여 저장한 이후 리스트를 배열로 변환하였습니다.
2. 키패드 누르기
- 1, 4, 7과 3, 6, 9는 왼손, 오른손이 정해져 있기에 if 문을 이용해 sb에 저장하였습니다.
- 2, 5, 8, 0을 선택해야할 때 선택해야할 번호와 현재 왼손, 오른손의 위치를 row값과 coL값을 이용하여 거리를 계산하였습니다.
- row = (num - 1) / 3, col = (num - 1) % 3
- 이후 왼손과 오른손의 거리를 비교하여 손을 결정한 이후 sb에 저장하였습니다.
---
- 리스트를 배열로 변경할 때 코드와 같이 for문이 아닌 stream을 활용하면 코드가 더 간단해질 수 있지만 stream에 익숙하지 않아 적용하지 못하였다.
```
List<Integer> list = Arrays.asList(1, 2, 3);
int[] arr = list.stream().mapToInt(Integer::intValue).toArray();
```
=> [3주차] 김재현 - 금 베스트앨범, 키패드 누르기

혁/3주차/금/베스트앨범.java, 혁/3주차/금/키패드_누르기.java
- 먼저 `Map`을 활용해 장르별 총 재생 횟수를 누적 저장(`genreTotal`).
- 또한, 같은 `Map`으로 장르별 노래 리스트(`songs`)를 저장했습니다.
- 장르별 총 재생 횟수를 기준으로 장르 순서를 정렬(`genreOrder`).
- 각 장르 리스트는 재생 횟수 내림차순, 동일 시 고유 번호 오름차순으로 정렬했습니다.
- 정렬된 리스트를 순회하며 각 장르에서 최대 2곡씩만 선택해 결과 리스트에 저장했습니다.
- 마지막으로 리스트를 배열로 변환해 반환했습니다.
- 각 숫자 키를 2차원 좌표 `(row, col)`로 정의하여 손 위치와의 거리를 계산합니다.
- 왼손 엄지는 `*` 위치 `(3, 0)`에서 시작
- 오른손 엄지는 `#` 위치 `(3, 2)`에서 시작
- 
- 왼쪽 열 숫자 `1, 4, 7`은 항상 왼손으로 누릅니다.
- 오른쪽 열 숫자 `3, 6, 9`는 항상 오른손으로 누릅니다.
- 숫자 `2, 5, 8, 0`은 현재 왼손과 오른손 위치에서 해당 번호까지의 맨해튼 거리(행 차이 + 열 차이)를 계산합니다.
- 거리가 더 가까운 손으로 누릅니다.
- 만약 거리가 같으면, 사용자의 손잡이(`hand`)에 따라 오른손잡이는 오른손, 왼손잡이는 왼손을 사용합니다.
- 누른 손의 위치를 해당 숫자의 좌표로 갱신합니다.
- 누른 손을 `"L"` 또는 `"R"`로 결과 문자열에 추가합니다.
=> [3주차] 장혁 - 금 베스트앨범, 키패드 누르기

유민/3주차/금/베스트앨범.java, 유민/3주차/금/키패드_누르기.java
1. 베스트앨범  
- 장르별 총 재생 수를 Map으로 계산하고, 각 장르별 곡 리스트를 따로 모아 저장했습니다.  
- 장르의 총 재생 수를 기준으로 장르를 정렬한 뒤, 각 장르에서 재생 수가 높은 노래 2곡을 선택했습니다.  
- 곡은 재생 수 기준으로 정렬하고, 같으면 고유 번호 오름차순으로 정렬했습니다.  
2. 키패드 누르기  
- 각 손의 현재 위치를 숫자로 저장하면서, 누를 번호에 따라 왼손/오른손을 결정했습니다.  
- 가운데 숫자는 왼손, 오른손 각각의 거리를 구해 비교했습니다.  
- 거리가 같으면 입력으로 주어진 hand 값(left/right)에 따라 결정했습니다.
=> [3주차] 이유민 - 금 베스트앨범, 키패드 누르기

아빈/3주차/금/베스트앨범.java, 아빈/3주차/금/키패드 누르기.java
- 베스트앨범
- 해당 문제는 장르별 가장 많은 재생 수를 기록한 장르를 최대 2개씩 많은 순서대로 판별하여 출력하는 문제였습니다.
- Map을 활용하여 저장된 곡의 장르별 재생수를 비교하여 출력하려 했으나, 재생수를 비교하여 판별해내는 과정을 써내는데에 어려움이 많았습니다..
- 첫 정렬에서 장르별 더 높은 총 재생수를 가진 장르 순으로 정렬 하고 두 번째 정렬에서 장르별 가장 높은 재생수를 최대 2개씩 골라내는 과정을 거쳐 문제를 해결할 수 있었습니다.
- 키패드 누르기
- 해당 문제는 키패드를 누를 때 어느 손가락으로 누를 지 판별하여 출력해내는 문제였습니다.
- #을 0,0으로 가정하고 3을 3,3으로 가정하여 좌표를 활용하여 문제를 해결하려 하였습니다. 
- 1, 4, 7과 3, 6, 9는 어차피 각각 왼손과 오른손으로 무조건 누르기 때문에 문자열에 추가 후 좌표만 이동하였습니다.
- 2, 5, 8, 0은 각 x,y차를 활용하여 왼손과 오른손 중 어느 손이 더 가까운지, 만약 같다면 주 손이 어디인지에 따라 문자열을 추가하고 해당 손의 좌표를 이동시켜 주었습니다.
- 조건식을 빼먹고 해서 문제가 있었지만, 생각보다 어려운 문제는 아니었던 것 같습니다
=> [3주차] 조아빈 - 금 베스트 앨범, 키패드 누르기

지은/3주차/금/베스트앨범.java, 지은/3주차/금/키패드 누르기.java
- 개인적으로 정말 어려웠던 문제... 해시가 손에 익지 않아서 좀 어렵게 느껴졌습니다.
- 다른 사람의 풀이를 참고해가며 구조를 이해하는 데 집중했습니다.
- 장르별 총 재생 수와 곡 리스트를 해시맵으로 분리해 저장  
- 장르별 총 재생 수 기준 정렬 → 곡 리스트는 재생 수와 인덱스 기준 이중 정렬  
- 각 장르에서 최대 2곡까지 추출해 최종 결과를 구성
- 키패드의 숫자를 누를 때, 어떤 손(왼손/오른손)을 사용하는지를 문자열로 반환하는 문제
- 왼손(1, 4, 7), 오른손(3, 6, 9), 나머지(2, 5, 8, 0)은 더 가까운 손으로 누르기
- 거리가 같다면 사용자의 hand 기준으로 판단
- 거리 계산은 아래처럼 키패드를 좌표로 표현하여 |x1 - x2| + |y1 - y2| 공식 적용
```
1(0,0)   2(0,1)   3(0,2)
4(1,0)   5(1,1)   6(1,2)
7(2,0)   8(2,1)   9(2,2)
*(3,0)   0(3,1)   #(3,2)
```
=> [3주차] 한지은 - 금 베스트앨범, 키패드 누르기

재현/4주차/월/길 찾기 게임.java
1. 길 찾기 게임
- 각 노드들을 Point 클래스를 이용하여 Y 좌표는 내림차순, X 좌표는 오름차순으로 정렬하였습니다.
- 정렬된 Point들을 이용하여 첫 번째 노드를 root로 선언하고 나머지 노드들은 재귀를 통해 왼쪽/오른쪽 서브트리에 삽입하는식으로 구현하였습니다.
- 전위 순회와 후위 순회의 결과를 리스트를 이용해 결과값을 저장하였습니다.
- 최종적으로 저장된 리스트를 배열로 변환하여 answer[0]과 answer[1]에 저장했습니다.
---
아쉬운점
- Point 클래스와 TreeNode 클래스를 별도로 정의하지 않아도 구현이 가능했는데 따로 정의해서 데이터 가져오는 과정에서 복잡했다.
- TreeNode에 x, y, index를 한 번에 포함시키면 데이터를 한 번에 처리하고 관리하기 더 효율적일 것 같다.
=> [4주차] 김재현 - 월 길 찾기 게임

아빈/4주차/월/길찾기게임.java
- 길 찾기 게임
- 해당 문제는 이진트리를 구현하여 전위순회, 후위순회에 따라 해당 노드의 인덱스를 배열에 담아 출력해내는 문제였습니다.
- 처음 Map으로 구현해보려 했으나 정렬이나 for문도 너무 많아지면서 구현에 힘들어 다른 분들의 풀이를 찾아보며 풀게 되었습니다.
- 필드로 인덱스, 각 좌표 연결 노드를 포함한 Node 클래스를 구현하였고, 트리 생성과 각 순회 메서드는 재귀 호출을 이용하여 연결 및 순회를 진행하여 해결할 수 있었습니다.
=> [4주차] 조아빈 - 월 길찾기 게임

하나/4주차/길찾기게임.java
1. 노드 번호와 함께 nodes 리스트 생성
2. y는 내림차순으로, x는 오름차순으로 정렬 -> 루트 잡기
3. 정렬된 순서대로 트리를 구성
4. 전위 순회, 후위 순회 실행
=> [4주차] 김하나 - 월 길 찾기 게임

경조/4주차/월/길찾기게임.java
- 각 노드를 Node 클래스로 구현했습니다.
- Node 배열인 nodes에 각 노드를 넣어준 후 Arrays.sort를 이용하여 y 값이 같을 시 x 값 오름차순 정렬, y 값이 같지 않다면 y 값 내림차순 정렬을 해주었습니다.
- 정렬해준 뒤 nodes[0]을 root로 지정해주었습니다.
- nodes의 길이만큼 반복하며 insertNode를 수행해줬습니다. (insertNode는 재귀 함수로 수행됩니다)
- answer[2][nodeinfo.length] 크기로 지정해준 뒤에
- preorder를 수행할 때는 answer[0][idx++]에 value 값을 넣어줬습니다. (idx는 0부터, preorder 재귀 함수로 수행)
- postorder를 수행할 때는 answer[1][idx++]에 value 값을 넣어줬습니다. (idx는 0부터, postorder 재귀 함수로 수행)
- 트리 형식의 문제를 오랜만에 접해서 좀 많이 참고했던 것 같습니다. 조만간 혼자서 다시 풀어보려고 합니다.
=> [4주차] 정경조 - 월 길 찾기 게임

재현/4주차/금/이중우선순위큐2.java
1. 이중우선순위큐
- minHeap과 maxHeap이라는 이름을 가진 PQ를 두개 만들어 최솟값과 최댓값을 관리
- 최소값 또는 최대값을 삭제할 때 maxHeap과 minHeap에서 각각 poll 과 remove를 이용하여 pq에서 제거
- 입력할 때에는 maxHeap minHeap 둘 다 입력
=> [4주차] 김재현 - 금 이중우선순위큐

경조/4주차/금/이중우선순위큐.java
- <숫자, 개수> 형태로 저장하는 TreeMap을 사용했습니다.
- I 명령어의 경우 키가 중복해서 들어가는 경우 개수 값을 getOrDefault를 통해 1씩 증가 시켜줬습니다.
- D 명령어의 경우 삼항 연산자를 통해 num이 1이면 tree의 마지막 값, 아니라면 tree의 첫 번째 값을 삭제 해주는 작업을 수행했습니다.
- 초반에 우선순위큐로 구현하다가 TreeMap으로 구현하니 생각보다 쉬웠던 문제였습니다.
=> [4주차] 정경조 - 금 이중우선순위큐

아빈/4주차/금/이중우선순위큐.java
- 이중우선순위 큐
- 해당 문제는 명령어들을 각각 처리하고 남아있는 수들 중에서 최댓값과 최솟값을 반환하는 문제였습니다.
- 처음 구현 하였을 때 우선 순위 큐 두 개를 활용하여 문제를 해결하려 하였으나, 삭제 시 제대로된 반환값이 나오지 않아 문제가 생겼었습니다.
- 해설을 참고하여 두 개의 우선순위 큐가 아닌 하나의 자료구조로 관리하기 위해서 TreeMap을 활용하여 해결할 수 있었습니다.
=> [4주차] 조아빈 - 금 이중우선순위 큐

지은/4주차/금/이중우선순위 큐.java
- PriorityQueue 두 개 사용(최소 힙 / 최대 힙)
- 삽입 연산 시 두 힙에 모두 삽입, 
- 삭제 연산 시 한 힙에서 poll() 한 후, 다른 힙에서 remove()로 동기화
- 최종적으로 큐가 비어있으면 [0,0], 아니면 [최댓값, 최솟값] 반환
=> [4주차] 한지은 - 금 이중우선순위 큐

유민/4주차/금/이중우선순위큐.java
- 최소 힙(minHeap), 최대 힙(maxHeap) 두 개를 동시에 유지하도록 했다.
- 삽입 시 두 힙에 모두 추가했다.
- 삭제 시 해당 힙에서 poll(), 다른 힙에서는 remove(value)로 동기화하고
- 최종적으로 힙이 비어 있으면 [0, 0], 아니면 [maxHeap.peek(), minHeap.peek()] 반환
- 삽입과 삭제 연산이 섞여 있어서 흐름 정리가 중요했다....
- 중간에 delete 연산 조건 분기 구조가 꼬이면서 한 번 문제 해결하기 어려웠는데 연산 종류별로 조건 분리를 명확히 하니까 훨씬 구조가 단순해졌다.
=> [4주차] 이유민 - 금 이중우선순위큐

혁/4주차/금/이중우선순위큐.java, 혁/5주차/월/타겟_넘버.java
#문제 풀이
- `"I n"`: 숫자 n을 큐에 삽입
- `"D 1"`: 큐에서 최댓값 삭제 (큐가 비어있으면 무시)
- `"D -1"`: 큐에서 최솟값 삭제 (큐가 비어있으면 무시)
- 모든 연산이 끝난 후 큐가 비어있으면 `[0, 0]` 반환, 아니면 `[최댓값, 최솟값]` 반환
- **TreeMap<Integer, Integer> map**
- 키는 숫자, 값은 해당 숫자의 개수
- 키가 오름차순으로 정렬되어 있어 최솟값과 최댓값을 쉽게 구할 수 있음
1. 숫자를 삽입할 때는 숫자의 개수를 증가시킴
2. 삭제 연산 시
- `D 1`: 최댓값(`map.lastKey()`)을 찾아 개수를 1 감소시키거나, 개수가 1이면 키를 삭제
- `D -1`: 최솟값(`map.firstKey()`)을 찾아 개수를 1 감소시키거나, 개수가 1이면 키를 삭제
3. 연산 후 맵이 비어있으면 `[0, 0]` 반환, 아니면 최댓값과 최솟값 반환
=> [4주차] 장혁 - 금 이중우선순위큐

하나/4주차/금/이중우선순위큐.java
- PriorityQueue를 두 개 사용해서 하나는 최소 힙, 하나는 최대 힙으로 사용
- 삭제 명령이 들어오면 poll로 하나의 힙에서 꺼내고 그 값을 다른 큐에서도 remove로 제거
- 큐가 비어있지 않으면 각각 peek로 최대/최소값을 구해 반환한다.
=> [4주차] 김하나 - 금 이중우선순위큐

재현/5주차/월/타겟 넘버.java
1. 타겟 넘버
- DFS를 이용하여 모든 경우의 수를 확인
- 종료 케이스는 마지막 연산까지 끝난 경우이며 그때 합이 target과 같다면 answer를 하나씩 증가시켰다.
- 재귀 케이스는 더하기와 빼기 두개 뿐이니 두개의 경우를 DFS 재귀를 통해 문제를 해결하였습니다.
=> [5주차] 김재현 - 월 타겟 넘버

유민/5주차/월/타겟넘버.java
- 큐를 이용해서 합을 관리하는 방식으로 bfs를 돌렸다.
- 처음에는 합이 0인 상태로 시작했다.
- numbers 배열을 순서대로 하나씩 보면서, 현재 큐에 있는 값에 + 또는 -를 적용해서 새로 추가했다.
- numbers를 다 돌고 난 뒤, 큐에 남은 값 중 target과 같은 값을 count했다.
- 처음에는 for문 안에서 queue.size()를 바로 가져와서 돌렸는데,  
큐에 값을 빼고 추가하는 과정에서 사이즈가 계속 변했다.
- 그래서 같은 층을 다 못 돌고 중간에 깨지는 문제가 있었다.
- for문 시작할 때 큐의 사이즈를 따로 저장하고, 그 사이즈만큼만 돌도록 고쳤다.
- 덕분에 BFS 층별 탐색이 제대로 유지돼서 원하는 결과를 얻을 수 있었다.
=> [5주차] 이유민 - 월 타겟넘버

혁/5주차/월/타겟_넘버.java
- 주어진 숫자 배열 `numbers`의 요소들에 `+` 또는 `-` 연산을 적용
- **타겟 넘버** `target`을 만드는 경우의 수를 구함
- **DFS (Depth-First Search, 깊이 우선 탐색)** 를 이용하여 모든 가능한 경우를 탐색
- 매 숫자마다 `+` 또는 `-`를 선택하는 2가지 방법을 구현한다.
- numbers의 모든 요소를 사용했을 때 합이 target과 같으면 경우의 수를 1개 추가
=> [5주차] 장혁 - 월 타겟 넘버

재현/5주차/수/게임 맵 최단거리.java, 재현/5주차/수/여행경로.java
1. 게임 맵 최단거리
- bfs을 이용하여 갈 수 있는 모든 경로에 대한 탐색
- visited 배열을 통해 해당 칸에 도달하려면 몇번이 가야하는지 저장
- dr, dc를 미리 선언함으로써 가로 방향, 세로 방향에 대한 이동 처리
2. 여행경로
- DFS를 이용하여 가장 빠른 결과에 대해 탐색
- 나올 수 있는 경로 중 가장 빠른 경로를 출력해야하므로 주어진 tickets 배열을 정렬
- dfs의 결과를 boolean을 반환하게 해서 첫 번째 경로가 구해지면 다른 탐색들은 종료
---
- `String[] answer = dq.toArray(new String[0]);` 이 명령어를 통해 deque를 array로 변경이 가능했다.
=> [5주차] 김재현 - 수 게임 맵 최단거리, 여행경로

혁/5주차/수/게임_맵_최단거리.java, 혁/5주차/수/여행경로.java, 혁/6주차/월/모음사전.java, 혁/6주차/월/전력망을_둘로_나누기.java
- `1`은 이동할 수 있는 칸, `0`은 벽으로 이동할 수 없는 칸인 2차원 배열 `maps`가 주어짐
- 시작 위치 `(0,0)`에서 도착 위치 `(n-1,m-1)`까지 **최단 경로로 이동**하는 데 필요한 칸의 수를 반환
- 이동은 **상, 하, 좌, 우**로만 가능
- 도착할 수 없다면 `-1` 반환
- **BFS (너비 우선 탐색)** 사용
- 큐를 이용해 현재 위치에서 이동 가능한 모든 방향으로 탐색
- 각 위치를 한 번만 방문하도록 `visited` 배열 사용
- 가장 먼저 도착점에 도달한 경우가 **최단 거리**이므로, 도착하자마자 거리 반환
- BFS는 최단거리 탐색에 적합함
---
- 주어진 `tickets` 배열에서 각 티켓은 `[출발지, 도착지]`
- **"ICN"** 공항에서 출발하여 모든 티켓을 **정확히 한 번씩 사용**
- 가능한 경로 중 **알파벳 순으로 가장 앞서는 경로**를 반환
- **DFS (깊이 우선 탐색)** + 백트래킹
- 현재 위치에서 출발 가능한 티켓을 **정렬**하여 탐색
- 사용 여부를 표시하는 `visited` 배열로 각 티켓을 **한 번씩만 사용**
- 모든 티켓을 사용한 경로가 발견되면, 해당 경로를 반환
- 여러 경로가 있을 경우 알파벳 순으로 가장 앞선 경로를 반환하기 위해 **정렬된 티켓 목록** 사용
=> [5주차] 장혁 - 수 게임 맵 최단거리, 여행경로

경조/5주차/수/게임맵최단거리.java, 경조/5주차/수/여행경로.java
- 상하좌우를 이동하면서 최단경로를 체크해야하는 문제였습니다.
- 최단 경로 문제는 BFS가 제일 적합해 BFS 방식으로 풀었습니다.
- 2차원 배열 visited와 distance를 통해 방문했는지, 거리가 얼마나 되는지 확인했습니다.
- dx, dy 배열은 상하좌우 이동하기 위해 선언했습니다.
- 무조건 ICN 공항에서 시작하고 여러 여행 경로가 있다면 알파벳 순서가 제일 빠른 여행 경로를 찾아내는 문제였습니다.
- DFS를 사용하기 좋은 문제였고 매개변수를 정하는 것이 중요했던 것 같습니다.
- 백트래킹을 하기 위해서 방문한 visited 배열을 다시 초기화해주었습니다.
- ArrayList를 사용한 pathList에 경로들을 저장하고 문자열 비교로 정렬하였습니다.
- pathList에 저장할 때 path 배열을 그대로 저장하게 되면 pathList에 저장된 값도 변경되어서 clone()을 통해서 복사해서 넣어줬습니다.
=> [5주차] 정경조 - 수 게임 맵 최단거리, 여행경로

혁/6주차/월/모음사전.java, 혁/6주차/월/전력망을_둘로_나누기.java
- 사용 가능한 알파벳은 `"A", "E", "I", "O", "U"` 다섯 가지
- 이 알파벳들로 만들 수 있는 길이 1~5의 모든 단어 중에서
- 특정 단어가 **사전에서 몇 번째에 위치하는지**를 반환
- 가능한 모든 조합을 생성하지 않고, **자리별 가중치 계산**을 통해 바로 순번 계산
- 각 자리마다 선택할 수 있는 경우의 수를 미리 계산 (가중치)
- ex) 첫 자리는 총 5^4 + 5^3 + 5^2 + 5^1 + 1 = 781 가지 가능
- `A`부터 시작했을 때의 인덱스를 이용해 현재 문자의 가중치를 더함
- 각 문자 위치마다 `index * weight[i] + 1` 더해 최종 순서 도출
---
- 전선 정보 `wires`가 주어질 때,
- 전선 하나를 끊어 **두 전력망으로 나눌 때** 두 전력망 노드 수 차이의 **최솟값**을 구함
- 전선을 하나씩 끊고 나눠지는 두 네트워크의 노드 수를 비교
- 하나의 전선을 제외하고 그래프를 구성한 뒤, BFS로 연결된 노드 수를 셈
- 전체 노드 수에서 뺀 값을 통해 나머지 한 쪽 네트워크 크기 계산
- 두 네트워크의 노드 수 차이를 구해 최소값 갱신
=> [6주차] 장혁 - 월 모음사전, 전력망을 둘로 나누기

아빈/6주차/월/모음사전.java, 아빈/6주차/월/전력망을둘로나누기.java
- 모음사전
- 해당 문제는 모음으로만 이루어진 최대길이가 5인 모든 경우의 단어들 중에서 주어진 단어가 몇번째인지 출력하는 문제였습니다.
- 모든 경우의 단어를 만들기 위해 dfs를 활용하였습니다.
- 생성된 단어들의 리스트에서 주어진단어가 몇번째인지 출력시켜 문제를 해결하였습니다.
- 전력망을 둘로 나누기
- 해당 문제는 이어진 송전탑을 두 그룹으로 나누었을 때 송전탑의 개수가 최대한 차이가 안나게 나누면서 그룹별 개수차이가 얼마가 나는지 출력하는 문제였습니다.
- 주어진 송전탑 정보를 인접리스트로 변환하여 사용하였습니다.
- 그룹을 나누는 모든 경우의 수를 완전탐색을 통해  가장 차이가 적은 수를 반환하여 문제를 해결하였습니다.
=> [6주차] 조아빈 - 월 모음사전, 전력망을 둘로 나누기

유민/6주차/월/모음사전.java, 유민/6주차/월/전력망을_둘로_나누기.java
- DFS로 가능한 모든 조합을 만들어가며 정답 단어의 위치를 찾도록 구현
- count 변수를 통해 단어 생성 순서를 추적하고 목표 단어와 일치하면 해당 순서를 반환
- 조기 종료 처리를 위해 found를 사용
- 각 간선을 하나씩 끊어보며 두 서브트리 크기의 차이를 구함.
- 간선을 제거한 상태에서 DFS를 통해 한 쪽의 노드 개수를 구하고, n - count로 반대편 개수를 계산
- 모든 간선에 대해 탐색하고 최소 차이를 구함.
=> [6주차] 이유민 - 월 모음사전, 전력망을 둘로 나누기

하나/6주차/수/메뉴리뉴얼.java
1. 메뉴 리뉴얼
- 주문을 알파벳 순으로 정렬한 후 코스 길이의 조합을 구한다.
- 각 조합을 map에 저장하고 등장 횟수를 기록
- 등장 횟수가 최대값이면서 2 이상인 조합만 결과 리스트에 추가
- 마지막 정답을 사전순 정렬해서 반환
=> [6주차] 김하나 - 수 메뉴 리뉴얼

재현/6주차/수/메뉴 리뉴얼.java
1. 메뉴 리뉴얼
- course 요리 개수에 맞게 map과 max 초기화
- order을 문자로 바꿔 정렬을 한 이후 dfs를 이용하여 cr 개수에 맞는 경우의 수에 대해 완전 탐색
- map을 이용하여 똑같은 코스가 몇개씩 나왔는지 저장을 한 이후 가장 많은 결과를 result 리스트에 추가
- 최종적으로 result 리스트에 저장된 결과를 정렬하여 반환
=> [6주차] 김재현 - 수 메뉴 리뉴얼

혁/6주차/수/메뉴_리뉴얼.java
- 손님들이 주문한 단품 메뉴 조합(`orders`) 중에서  
- **2명 이상이 주문한 인기 조합**을 **코스 요리**로 선정하고자 합니다.
- 코스 요리는 정해진 길이들(`course` 배열)을 따릅니다.
- 각 길이별로 **가장 많이 주문된 조합들**을 찾아  
- 이를 **사전 순으로 정렬한 결과**를 반환합니다.
---
- 예: `"BAC"` → `"ABC"`
- 이유: 같은 조합이라도 순서를 맞춰야 중복 인식 가능
- **백트래킹(재귀)** 방식으로 조합 생성  
- 예: `"ACDE"`에서 길이 2이면 → `AC`, `AD`, `AE`, `CD`, `CE`, `DE` 등
- 등장 횟수가 **2 이상**인 조합 중  
- **최대 빈도수**를 가진 조합들만 선택
=> [6주차] 장혁 - 수 메뉴 리뉴얼

경조/5주차/월/타겟넘버.java, 경조/6주차/수/메뉴리뉴얼.java
- `<String, Integer>` 형태의 HashMap을 사용하여 코스 별 주문한 횟수를 저장했습니다
- 각 order를 char[] 배열로 담아주고 정렬해주어 AC, CA 같이 동일한 값이 순서가 다르게 저장되는 일이 없게 했습니다
- max 값을 가진 코스는 answerList에 추가해줬습니다
- answerList를 정렬하고 answer 배열에 넣어줬습니다
=> [6주차] 정경조 - 수 메뉴 리뉴얼

재현/6주차/금/불량 사용자.java
1. 불량 사용자
- isOk 함수를 통해 banned_id와 user_id 간에 일치하는지 확인
- dfs를 이용하여 완전 탐색
- result를 Set으로 선언함으로써 중복된 조합에 대해서 추가 X
- Bitmask를 이용하여 user_id의 몇 번째 항목이 사용되었는가 표시
---
- `bitmask & (1 << i)` : 결과가 1이라면 i 번째 유저는 사용된 것이고 0이라면 i 번째 유저는 사용되지 않음
- `bitmask | (1 << i)` : i 번째 유저를 사용할 때 bitmask에 i번 인덱스를 1로 변경하여 사용됨을 표기
=> [6주차] 김재현 - 금 불량 사용자

경조/6주차/금/불량사용자.java
- `isMatch` 함수를 선언하여 `user_id`와 `banned_id`가 일치하는지 체크했습니다.
- dfs를 사용했습니다.
- HashSet을 사용하여 banned_id에 걸리는 user_id를 저장할 때 중복되지 않게 했습니다.
=> [6주차] 정경조 - 금 불량 사용자

하나/6주차/금/불량사용자.java
1. 불량 사용자  
- banned_id의 *을 임의의 한 글자로 변경
- 각 banned_id에 대해 매칭 가능한 user_id 리스트를 찾음
- 중복되지 않은 조합을 모두 탐색 
- 조합의 순서가 다르더라도 같은 조합은 1개로 간주 (중복 제거 위해 Set을 사용)
=> [6주차] 김하나 - 금 불량 사용자

지은/6주차/금/불량 사용자.java
- user_id 배열에서 banned_id 패턴과 일치하는 ID 조합을 구하는 문제
- DFS + 백트래킹 사용해 모든 조합을 탐색
- Set<Set<String>>을 활용해 중복 조합 제거
- 패턴 매칭은 check() 함수로 구현
=> [6주차] 한지은 - 금 불량 사용자

아빈/6주차/금/불량사용자.java
- 불량 사용자
- 해당 문제는 주어진 user_id 들에서 banned_id에 있는 제제 목록에 따라 제제 받을 수 있는 id들 리스트의  경우의 수를 출력하는 문제였습니다.
- 기존에는 String 조합을 만든 후 문자열로 비교하여 중복을 제거하고 String.matches()를 통해 정규식을 통새서 제재아이디인지 확인 하는 방식으로 구현하였습니다.
- 해당 과정에서 시간을 줄일 수 있을 것 같다 생각하였는데 Set과 isMatch를 따로 직접 구현하여 시간을 대폭 줄일 수 있었습니다.
=> [6주차] 조아빈 - 금 불량사용자

재현/7주차/모의고사.java, 재현/7주차/카펫.java
1. 모의고사
- 1번, 2번, 3번 학생의 규칙을 first, second, third로 미리 작성
- 모든 문제에 대해 for문을 돌며 정답이 맞을 경우 anwer[인덱스]++을 이용하여 정답 수를 저장
- Math.max를 이용하여 가장 많이 맞은 문제 수를 구한 뒤 가장 많이 맞춘 학생을 List에 추가
- List를 Array로 변환
2. 카펫
- 전체 카펫의 개수를 이용하여 카펫이 만들어 질 수 있는 가로와 세로 길이를 계산
- brown은 테두리에만 존재가 가능하기 때문에 2 * (가로 + 세로 - 2) 개만 칠해질 수 있음
- 만들어 질 수 있는 가로 세로 길이에 대해 brown이 가능하면 결과를 저장하여 출력
=> [7주차] 김재현 - 월 모의고사, 카펫

경조/7주차/월/모의고사.java, 경조/7주차/월/카펫.java
---
- 문제 정답이 주어지면 1, 2, 3번 수포자가 각자 찍는 방식에서 정답을 가장 많이 맞춘 사람을 찾는 문제입니다.
- 각 수포자의 정답 방식을 `arr1`, `arr2`, `arr3`에 저장해줬습니다.
- 정답을 체크할 때 정답 방식 인덱스를 `i % arr.length`를 통해 체크해줬습니다.
---
- 카펫의 갈색, 노란색 개수를 통해 카펫의 가로, 세로 길이를 맞추는 문제입니다.
- 카펫의 중앙은 노란색, 테두리 1줄은 갈색으로 칠해져 있는 모양입니다.
- 노란색이 존재하려면 카펫은 최소 `3 * 3` 크기이고, 노란색은 `(가로 - 2) * (세로 - 2)`를 하면 구할 수 있게 됩니다.
=> [7주차] 정경조 - 월 모의고사, 카펫

아빈/7주차/월/모의고사.java, 아빈/7주차/월/카펫.java
- 모의고사
- 해당 문제는 세 명의 수포자가 문제를 찍는 번호의 패턴에 따라 누가 제일 많이 맞췄는지 출력해내는 문제였습니다.
- 주어지는 answer의 길이에 따라 반복문을 돌며 나머지 연산을 통해 해당 번호의 정답여부를 판단하여 최댓값을 반환 배열에 삽입하여 문제를 해결할 수 있었습니다.
- 카펫
- 해당 문제는 겉을 감싸는 갈색 사각형과 안을 채우는 노란색 사각형의 개수로 만들 수 있는  사각형의 가로와 세로의 사각형 개수를 출력하는 문제였습니다.
- 최소 높이인 3부터 반복문을 돌며 조건에 부합하는 가로 세로의 개수를 반환 배열에 삽입하여 문제를 해결할 수 있었습니다.
=> [7주차] 조아빈 - 월 모의고사, 카펫

지은/7주차/월/모의고사.java, 지은/7주차/월/카펫.java
- 수포자들의 정답 찍기 패턴이 반복되므로 각각 p1, p2, p3 배열로 정의
- 정답 배열 answers를 순회하며며 각 수포자의 정답 개수를 scores[]에 누적
- 최댓값 maxScore를 기준으로 최고 점수를 받은 수포자 번호를 list에 저장
- list는 stream()을 사용하여 int[]로 변환
- 정답 배열은 항상 [가로, 세로] 형태이므로 미리 int[2] 선언
- 전체 격자 수를 brown + yellow로 계산하여 total에 저장
- height는 테두리 고려하였을 때 최소 3부터 시작하므로 total의 약수 탐색
- yellow 영역은 (width - 2) \* (height - 2) == yellow 인 조합을 찾아 저장
=> [7주차] 한지은 - 월 모의고사, 카펫

지은/7주차/수/조이스틱.java, 지은/7주차/수/체육복.java
- lost, reserve 정렬 후, 여벌 옷 가진 도난 학생은 본인한테 우선 배정
- visited배열로 여벌 체육복 사용 여부 저장장
- 남은 도난 학생은 인접 번호(+1, -1)의 여벌 보유자에게 체육복을 빌림
- 수업 가능한 학생 수 = 전체 학생 수 - 도난 + 해결 인원 반환
- 각 알파벳 'A'에서 목표 문자로 바꾸는 최소 조작 횟수 계산
- 커서는 기본적으로 오른쪽으로 이동하고, 전체 길이 -1 로 초기화
- 중간에 연속된 A를 우회하거나 되돌아가는 방식으로 이동 최소값 탐색
- 문자 조작 횟수, 커서 이동 최소값을 더해 정답 반환
=> [7주차] 한지은 - 수 체육복, 조이스틱

하나/7주차/수/조이스틱.java, 하나/7주차/수/체육복.java
1. 체육복
- 배열로 학생 번호별 체육복 개수를 표현하고, 도난 -1, 여벌 +1로 표현한다.
- 체육복이 없는 학생을 순회하며 앞번호 또는 뒷번호에게 빌릴 수 있으면 빌린다.
- 마지막으로 체육복이 0 이상인 학생 수를 세어 반환한다.
2. 조이스틱
- 각 문자를 A로부터 바꾸는 데 필요한 최소 조작 횟수를 더한다.
- 커서 이동 시 A가 연속된 부분을 건너뛰기 위해 모든 커서 이동 경로의 최소 이동을 계산한다.
- 왼쪽 갔다가 오른쪽, 오른쪽 갔다가 왼쪽 등 다양한 방향 조합을 비교하여 가장 적은 이동을 구한다.
- 최종적으로 위/아래 조작 횟수 + 최소 커서 이동 횟수를 반환한다.
=> [7주차] 김하나 - 수 체육복, 조이스틱

혁/7주차/수/조이스틱.java, 혁/7주차/수/체육복.java, 혁/7주차/월/모의고사.java, 혁/7주차/월/카펫.java
1. **교집합 제거**
- 도난당했지만 여벌도 있는 학생은 자기 것만 입고 끝
- → `lost`와 `reserve`에서 제거
2. **정렬 후 앞뒤 번호 탐색**
- `reserve` 학생이 `lost - 1` 또는 `lost + 1`인 경우 체육복 빌려줌
3. **최종 인원 계산**
- 전체 학생 수에서 여전히 체육복 없는 학생 수를 뺀 값이 답
---
1. **위/아래 조작 최소값 계산**
- 각 문자마다 `A`에서 가까운 방향 선택 (`▲` 또는 `▼`)
2. **좌/우 이동 최소 경로 탐색**
- 기본적으로 오른쪽으로 쭉 가는 것부터 시작
- 중간에 `A`가 연속된 구간을 우회해서 돌아가는 방식이 더 짧을 수 있음
- `i` 지점까지 갔다가 되돌아오는 방식, 끝까지 갔다가 돌아오는 방식 등 비교
=> [7주차] 장혁 - 수 체육복, 조이스틱

경조/7주차/수/조이스틱.java, 경조/7주차/수/체육복.java
- HashMap을 이용해서 체육복 개수를 매칭했습니다.
- 각 문자를 A에서 변환하는데 위로 가는 횟수, 아래로 가는 횟수를 비교하여 최소값을 찾는다.
- 좌우 움직임은 순서대로 가는 것과, 뒤로 돌아가는 것 중 이동수가 적은 것, 처음부터 뒷부분을 먼저 입력하는 것 중에 최소 길이를 구합니다.
=> [7주차] 정경조 - 수 체육복, 조이스틱

유민/7주차/수/조이스틱.java, 유민/7주차/수/체육복.java
- 여벌 체육복을 가진 학생이 도난당한 경우를 먼저 처리하 앞뒤 번호 학생에게 체육복을 빌려주도록 했습니다.
- 여벌을 이미 사용했는지와 도난 학생이 빌렸는지를 별도 배열로 체크해서 중복 대여 예외 처리를 해줬습니다!
- 각 알파벳을 ‘A’에서 바꾸는 최소 조작 수와, 커서를 움직이는 최소 횟수를 분리해서 계산
- 커서 이동은 연속된 ‘A’ 구간을 고려해 오른쪽, 왼쪽, 우회 경로 중 최소값을 선택하는 방식으로 처리
=> [7주차] 이유민 - 수 체육복, 조이스틱

재현/7주차/금/큰 수 만들기.java
1. 큰 수 만들기
- 스택을 통해 왼쪽 숫자부터 삽입
- 아직 k만큼 숫자를 지우지 못했다면 다음 입력해야할 숫자보다 스택의 값이 클 때 까지 pop
- 모든 숫자를 돌았지만 k가 남을 경우 남은 k만큼 pop
- 최종적으로 구해진 스택을 StringBuilder를 통해 다시 문자열로 변환 후 반환
=> [7주차] 김재현 - 금 큰 수 만들기

아빈/7주차/금/큰수만들기.java
- 큰 수 만들기
- 해당 문제는 주어진 number에서 k 개수만큼 숫자를 제거하여 만들 수 있는 가장 큰 수를 출력하는 문제였습니다.
- 문자열을 만드는 과정은 k 만큼의 반복은 필요없기 때문에 number.length() - k 만큼 반복하였습니다.
- 안쪽 반복문에서 현재 들어갈 자릿수 인덱스 (i) 부터 최소 k개의 문자를 비교해야 하기 때문에 i + k 만큼 반복하도록 구현하였습니다.
- i 자리에 들어갈 수가 선택 되면 그 수 이후의 인덱스부터 탐색을 진행하도록 구현하였습니다.
- 안쪽 반복문이 끝날 때마다 각 자릿수 i 에 들어갈 문자를 추가하여 가장 큰 수를 만들 수 있었습니다.
=> [7주차] 조아빈 - 금 큰 수 만들기

혁/7주차/금/큰_수_만들기.java
- 왼쪽부터 숫자를 하나씩 스택에 넣으면서 진행
- 현재 숫자가 스택의 top보다 크면, top을 제거하고 현재 숫자를 push
- 이 과정을 **k번 제거할 때까지 반복**
- 끝까지 순회했는데도 k가 남아 있다면,
- 스택의 뒤쪽에서 숫자를 잘라냄  
→ 즉, 스택의 상위 숫자만 남김
- 스택에서 앞에서부터 `number.length() - k`개의 숫자를 꺼내서 문자열을 생성
=> [7주차] 장혁 - 금 큰 수 만들기

하나/7주차/큰수만들기.java
1. 큰 수 만들기  
- 자릿수마다 현재 선택 가능한 범위 중에서 가장 큰 수를 고른다.(그리디)
- idx를 기준으로 남은 숫자 중 최댓값을 선택하고, 선택된 위치 다음부터 다음 자릿수 탐색을 이어간다.
- 이 과정을 number.length() - k번 반복해 최종 결과를 반환한다.
=> [7주차] 김하나 - 금 큰 수 만들기

경조/7주차/금/큰_수_만들기.java
- 숫자 k개를 제거하여 가장 큰 숫자를 만드는 문제입니다.
- 숫자 선택 범위를 줄여가며 한 자리씩 선택합니다.
- 매번 가장 큰 숫자를 선택하고, 그 이후 탐색을 합니다.
- 총 `number.length() - k`개의 숫자를 선택해서 답을 만듭니다.
=> [7주차] 정경조 - 금 큰 수 만들기

지은/7주차/금/큰 수 만들기.java
- 앞자리부터 큰 숫자를 유지하도록, 더 작은 숫자는 제거
- 최대 k개까지 숫자를 제거하여 가장 큰 수 만들기
- 제거하고 남은 숫자는 StringBuilder 사용하여 문자열로 반환
=> [7주차] 한지은 - 금 큰 수 만들기

재현/8주차/월/숫자 카드 나누기.java, 재현/8주차/월/예산.java
1. 예산
- d 배열을 오름차순으로 정렬
- 적은 돈을 필요로 하는 부서부터 예산을 사용하며 budget이 부족하거나 다 소진할 때 까지 반복
- 최종적으로 예산을 지원해준 부서의 개수를 반환
2. 숫자 카드 나누기 
- gcd 함수를 통해 유클리드 호재법으로 a와 b의 최소 공약수를 구하는 함수 작성
- getGCD 함수를 통해 배열을 받아 배열 전체 숫자의 최소 공약수를 구하는 함수를 작성
- isDivisor 플래그를 사용하여 A에서는 나뉘지만 B에서는 나뉘지 않는 또는 B에서는 나뉘지만 A에서 나뉘지 않는지 확인
- 조건을 만족하는 숫자를 찾을 시에 answer를 업데이트하고 최종 answer를 반환
=> [8주차] 김재현 - 월 예산, 숫자카드 나누기

유민/8주차/월/숫자_카드_나누기.java, 유민/8주차/월/예산.java
- 각 배열의 최대공약수를 구한 뒤, 상대 배열의 모든 원소가 해당 값으로 나누어지지 않는지 검사
- 나눌 수 없는 쪽의 최대공약수 중 조건을 만족하는 값이 정답이 될 수 있으므로 두 경우를 모두 확인
- 조건 검사 함수는 배열 전체를 순회하며 하나라도 나누어 떨어지면 false를 반환
- 지원 금액 배열을 오름차순 정렬한 뒤 이진 탐색으로 최대 지원 가능한 부서 수를 탐색
- mid개의 부서를 지원할 수 있는지 여부를 판단하여 범위를 좁혀가며 탐색
- 지원 가능한 경우 answer를 갱신하고 left를 증가시켜 더 많은 부서 지원 가능성 탐색
=> [8주차] 이유민 - 월 예산, 숫자 카드 나누기

경조/8주차/월/숫자_카드_나누기.java, 경조/8주차/월/예산.java
- 정해진 예산 내에서 가장 많은 부서에 지원하는 문제입니다.
- 먼저 부서들이 요청한 금액을 오름차순으로 정렬해서 풀었습니다.
- 정렬한 뒤 예산이 0 이상일 때까지 차감하면서 지원되는 부서의 수를 카운트 해줬습니다.
- `arrayA`의 최대공약수, `arrayB`의 최대공약수를 구해 각 최대공약수가 반대쪽 숫자를 못 나누는 가장 큰 정수를 찾는 문제입니다.
- `유클리드 호제법` 알고리즘을 적용한 `gcd` 함수를 이용해 두 수 사이에서 최대공약수를 찾았습니다.
- `getGCD` 함수를 통해 배열 내에서 최대공약수를 구합니다.
- `isNotDivisible` 함수를 통해 최대공약수가 다른 쪽 배열의 요소를 나눌 수 있는지 확인합니다.
- 예를 들어 최대공약수가 각 배열에서 찾아 6, 7이 나오게 된다면 7을 결과로 반환해야하기 때문에
- `answer` 값을 `Math.max` 통해서 저장합니다.
=> [8주차] 정경조 - 월 예산, 숫자 카드 나누기

아빈/8주차/월/숫자카드나누기.java, 아빈/8주차/월/예산.java
- 예산
- 해당 문제는 정해진 예산을 얼마나 많은 인원이 사용할 수 있는지 출력하는 문제였습니다.
- 주어진 d 를 오름차순으로 정렬 후 반복문내에서 budget에서 차감해가면서 answer을 증가시켜 해결할 수 있었습니다.
- 숫자 카드 나누기
- 해당 문제는 조어진 주건에 부합하는 최대로 큰 양수 a를 출력하는 문제였습니다.
- 처음엔 각 배열에서 첫번째 수를 뽑아서 더 큰 수만큼 반복문을 돌며 조건을 통과하는 수를 출력해서 해결할 수 있었습니다.
- 두 번째로 유클리드 호재법을 적용과 검증 로직을 분해하여 가독성과 속도를 증가시킬 수 있었습니다.
=> [8주차] 조아빈 - 월 예산, 숫자 카드 나누기

지은/8주차/월/숫자 카드 나누기.java, 지은/8주차/월/예산.java
- 주어진 예산 budget 내에서 부서 별 요청 금액을 최대한 많이 지원해야 함.
- 요청 금액 배열 d를 오름차순으로 정렬하여 예산이 적게 드는 부서부터 우선 지원
- 정렬된 배열을 순회하며 예산에서 금액을 하나씩 차감
- 예산이 0보다 작아지는 순간 반복을 중단하고, 지금까지 지원한 부서의 수를 반환
- arrayA, arrayB 의 모든 원소를 나눌 수 있는 최대공약수 gcdA, gcdB를 각각 계산
- 각 최대공약수(gcd)는 상대 배열의 어떤 원소도 나눌 수 없어야 후보가 될 수 있음
- 조건 만족 시 해당 값을 후보로 선택
- 두 후보 중 최댓값을 정답으로 반환
=> [8주차] 한지은 - 월 예산, 숫자 카드 나누기

하나/8주차/월/숫자 카드 나누기.java, 하나/8주차/월/예산.java
1.  예산
- 부서별 신청 금액을 오름차순 정렬 
- 작은 금액부터 차례대로 예산에서 차감
- 예산이 차감된 부서 수를 카운트 하고 최종적으로 반환한다.  
2. 숫자 카드 나누기
- 각 배열의 최대 공약수를 구함
- 한 배열의 최대 공약수가 나머지 한 배열의 모든 숫자를 나누지 못한다면 후보가 됨
- 두 경우 중 큰 값을 반환
=> [8주차] 김하나 - 월 예산, 숫자 카드 나누기

지은/8주차/수/입국심사.java
- 사람 n명을 심사관들이 주어진 시간 안에 처리 가능한 최소 시간을 구하는 문제
- 시간 범위를 이분 탐색하여, 해당 시간 동안 처리 가능한 인원이 n명 이상인지 검사
- midTime 동안 각 심사관이 처리 가능한 인원을 합해서 조건 만족하면 시간을 줄이고, 부족하면 늘려가며 최소값으 탐색
=> [8주차] 한지은 - 수 입국심사

하나/8주차/수/입국심사.java
1. 가능한 시간 범위는 1분부터 (가장 느린 심사관 시간 × 사람 수)까지
2. 각 시간(mid)마다 해당 시간 동안 몇 명까지 심사가 가능한지 계산한다
3. 심사 가능한 인원이 n명 이상이면 시간을 줄여보고, 아니면 늘려본다
4. 가능한 최소 시간을 최종 반환한다.
=> [8주차] 김하나 - 수 입국심사

아빈/8주차/수/입국심사.java
- 입국심사
- n명의 인원이 주어진 times의 소요시간들의 심사시간에 따라 모든 인원이 심사를 받는데 걸리는 최소 시간을 출력하는 문제입니다.
- 완전탐색을 사용하여 탐색을 진행하기에는 범위가 매우 큰 숫자이기 때문에 이분탐색을 적용하여 해결할 수 있었습니다.
- 탐색 범위를 0 ~ 최대 소요시간으로 잡고 처리 가능한 인원이 n 보다 작을 때와 아닐 때 조건에 따라 탐색범위를 좁혀가며 해결할 수 있었습니다.
=> [8주차] 조아빈 - 수 입국심사

재현/8주차/수/입국심사.java
1. 입국심사
- 처음에는 배열에 가능한 시간과 인원수를 작성해서 풀어보려고 했지만 n이 커서 시간초과가 발생
- 숫자 찾기 업다운 문제와 같이 최댓값과 최솟값의 중앙값을 이용하여 문제를 풀이
- 중앙값을 하였을 때 결과가 n보다 크면 최댓값을 mid - 1로
-결과가 n보다 작으면 최솟값을 mid + 1로 변경하면서 범위를 줄여가며 문제 해결
=> [8주차] 김재현 - 수 입국심사

하나/8주차/금/징검다리.java
1. 징검다리
- mid를 거리의 최소값 후보로 지정한다.
- 두 바위 사이의 거리가 mid보다 작으면 바위를 제거하고
- 작지 않으면 바위를 유지하고 위치를 갱신한다.
- 제거한 바위 개수가 n 이하일 경우 mid 값은 유효하기 때문에 더 큰 거리를 시도한다.
- 제거한 바위가 n을 초과할 경우 mid 값이 너무 큰 값이기 때문에 거리를 줄여본다.
=> [8주차] 김하나 - 금 징검다리

지은/8주차/금/징검다리.java
- mid를 최소 거리 후보로 두고, 돌 사이 간격이 mid보다 작으면 removed를 증가시킴
- removed가 n 이하면 최소 거리 mid를 만족할 수 있으므로 거리를 늘림
- n 초과면 돌을 너무 많이 제거해야 하므로 최소 거리 범위 축소
- 조건을 만족하는 최소 거리 중 최댓값을 찾아 반환
=> [8주차] 한지은 - 금 징검다리

하나/9주차/게임맵최단거리.java, 하나/9주차/괄호회전하기.java, 하나/9주차/단어변환.java, 하나/9주차/보물지도.java, 하나/9주차/신고결과받기.java, 하나/9주차/전력망을둘로나누기.java
``` dfs를 사용하여 풀이 ```
- words에 target이 없는 경우는 변환 불가 → 0 반환
- DFS로 모든 변환 가능한 경우를 탐색
- 한 번에 한 글자만 다른 단어만 다음 후보로 탐색
- begin == target이 되는 순간, 그때까지의 변환 횟수를 answer에 저장  
``` bfs를 사용하여 풀이 ```
- bfs 탐색을 위해 큐 사용
- (0,0)부터 시작해서 네 방향으로 이동
- 이동 가능한 칸(==1)은 현재 칸의 거리 +1로 갱신
- 목표 지점 (n-1, m-1)에 도달하면 거리 반환
- 도달할 수 없으면 -1 반환  
``` bfs를 사용하여 풀이 ```
- 모든 전선을 하나씩 끊는 과정 수행
- 끊은 전선을 제외하고 그래프 구성
- bfs를 통해 한 쪽 전력망의 노드 수를 계산
- 두 전력망의 차이 = | n - count - count |
- 그 중 최소값을 정답으로 선택  
``` Map, Set을 활용해 중복 제거, 신고 횟수 카운트 하여 풀이```
- Set으로 신고 중복 제거하고, 신고 당한 횟수를 Map으로 세기
- k번 이상 신고당한 유저만 정지 대상으로 분류
- 내가 신고한 사람 중 정지된 사람 수 만큼 메일 카운트 증가
``` Stack을 사용해 풀이 ```
- 문자열 s를 길이만큼 회전 시도
- 매 회전마다 괄호 문자열이 유효한지 검삭 → 스택 사용
- 유효하면 정답 카운트 증가
``` bfs를 사용하여 풀이 ```
- (1,1)에서 시작하여 BFS로 (n,m)까지 최단 시간 탐색
- 이동 시 신발 안 씀, 신발 씀 두 가지 상태를 함께 관리
- 방문 …
=> [9주차] 김하나 - 알고리즘 중간고사 대비

재현/9주차/중간고사 대비/게임 맵 최단거리.java, 재현/9주차/중간고사 대비/괄호 회전하기.java, 재현/9주차/중간고사 대비/단어 변환.java, 재현/9주차/중간고사 대비/보물지도.java, 재현/9주차/중간고사 대비/신고 결과 받기.java, 재현/9주차/중간고사 대비/전력망을 둘로 나누기.java
1. 괄호 회전하기
- isOk 함수를 통해 괄호가 적절히 배치 되어있는지 확인하여 true / false 반환
- Deque을 통해서 맨 앞 괄호를 맨 뒤로 옮기는 방식으로 괄호를 회전
- for문을 이용하여 회전을 진행하며 isOk에서 true가 반환되면 answer++하고 최종 answer 반환
2. 게임 맵 최단거리
- Point 클래스를 이용하여 좌표 관리
- dr, dc 배열을 미리 선언하여 상, 하, 좌, 우 이동 관리
- bfs 이용하여 최단거리 계산
3. 단어 변환
- isDiffOne 함수를 통해 단어가 한개만 같은지 확인한 이후 ture / false 반환
- 맨 처음 begin과 한개 차이 나는 단어들을 큐에 대입 후 visited 1 증가
- 이후 bfs를 진행하며 이전 visited에 1을 증가시키며 진행
- target에 도달하면 target의 visited 값을 이용하여 최단거리 계산
4. 신고 결과 받기
- Set을 이용하여 중복되는 신고는 제거
- count라는 Map을 이용하여 신고 횟수 저장
- person이라는 Map을 이용하여 누가 누구를 신고하였는지 저장
- 신고 내역을 다 정리한 뒤 person Map에서 신고한 사람의 리스트를 불러와서 k번 이상이면 c++
- 최종적으로 신고한 사람의 answer 인덱스에 c값을 대입하여 answer를 반환
5. 전력망을 둘로 나누기
- List 배열을 이용하여 wire 관리
- 전체 wire들을 반복을 해가며 하나씩 제거 한 뒤 bfs 진행
- 한쪽 방향에서 구해진 개수를 count라고 하면 두 네트워크의 차이는 …
=> [9주차] 김재현 - 알고리즘 중간고사 대비

하나/9주차/게임 맵 최단거리.java, 하나/9주차/괄호회전하기.java, 하나/9주차/단어변환.java, 하나/9주차/보물지도.java, 하나/9주차/신고 결과 받기.java, 하나/9주차/전력망을둘로나누기.java
``` dfs를 사용하여 풀이 ```
- words에 target이 없는 경우는 변환 불가 → 0 반환
- DFS로 모든 변환 가능한 경우를 탐색
- 한 번에 한 글자만 다른 단어만 다음 후보로 탐색
- begin == target이 되는 순간, 그때까지의 변환 횟수를 answer에 저장  
``` bfs를 사용하여 풀이 ```
- bfs 탐색을 위해 큐 사용
- (0,0)부터 시작해서 네 방향으로 이동
- 이동 가능한 칸(==1)은 현재 칸의 거리 +1로 갱신
- 목표 지점 (n-1, m-1)에 도달하면 거리 반환
- 도달할 수 없으면 -1 반환  
``` bfs를 사용하여 풀이 ```
- 모든 전선을 하나씩 끊는 과정 수행
- 끊은 전선을 제외하고 그래프 구성
- bfs를 통해 한 쪽 전력망의 노드 수를 계산
- 두 전력망의 차이 = | n - count - count |
- 그 중 최소값을 정답으로 선택  
``` Map, Set을 활용해 중복 제거, 신고 횟수 카운트 하여 풀이```
- Set으로 신고 중복 제거하고, 신고 당한 횟수를 Map으로 세기
- k번 이상 신고당한 유저만 정지 대상으로 분류
- 내가 신고한 사람 중 정지된 사람 수 만큼 메일 카운트 증가
``` Stack을 사용해 풀이 ```
- 문자열 s를 길이만큼 회전 시도
- 매 회전마다 괄호 문자열이 유효한지 검삭 → 스택 사용
- 유효하면 정답 카운트 증가
``` bfs를 사용하여 풀이 ```
- (1,1)에서 시작하여 BFS로 (n,m)까지 최단 시간 탐색
- 이동 시 신발 안 씀, 신발 씀 두 가지 상태를 함께 관리
- 방문 …
=> [9주차] 김하나 - 중간고사 알고리즘 대비

경조/9주차/게임_맵_최단거리.java, 경조/9주차/괄호_회전하기.java, 경조/9주차/단어변환.java, 경조/9주차/보물지도.java, 경조/9주차/신고_결과_받기.java, 경조/9주차/전력망_둘로_나누기.java
- bfs 사용하여 풀이
- Move 클래스 정의하여 현재 위치, 거리값 저장
- check 함수로 유효한 범위인지 확인
- bfs 사용하여 풀이
- Word 클래스 정의하여 현재 단어, 횟수 저장
- diffCount 함수로 다른 단어 개수 확인
- bfs 사용하여 풀이
- check 함수 이용하여 유효한 범위인지 확인
- User 클래스 정의하여 현재 위치, 거리, 점프 사용여부(1: 미사용, 0: 사용) 저장
- boolean 3차원 배열로 구성하여 같은 위치더라도 점프 있고 없고에 따라 다르게 방문처리
- bfs 사용하여 풀이
- 간선 정보를 가지고 인접리스트로 구성
- 간선을 하나씩 제거하면서 bfs 수행하며 두 네트워크 차이는 최솟값으로 저장하기
- 동일한 신고는 1번으로 처리하기 위한 reportSet
- <유저, 신고당한 횟수>를 저장하는 countMap
- <유저, 신고목록>을 저장하는 reportMap
- 정지당한 유저를 저장하는 banned
- 신고목록에 정지 당한 유저가 있으면 1씩 증가시켜줌
- String으로 주어진 괄호를 toCharArray를 통해서 Character 형태로 queue에 저장
- check 함수를 통해서 괄호가 올바르게 구성됐는지 확인 이때 큐는 복사해서 전달
- check 함수에서는 stack을 이용하여 괄호 확인
=> [9주차] 정경조 - 알고리즘 중간고사 대비

유민/9주차/게임맵최단거리.java, 유민/9주차/괄호회전하기.java, 유민/9주차/단어변환.java, 유민/9주차/보물지도.java, 유민/9주차/신고결과받기.java, 유민/9주차/전력망을둘로나누기.java
- BFS로 최단거리 탐색  
- visited로 중복 방문 방지  
- 도착 못하면 -1 반환  
- 일반 이동 + 점프 이동 (한 번만 가능)  
- visited[y][x][jump 여부]로 방문 체크  
- BFS로 최단 거리 구함  
- 문자열 회전하며 스택으로 유효성 검사  
- 올바른 괄호면 count++  
- 한 쌍이라도 안 맞으면 false  
- 한 글자 차이 단어만 연결  
- BFS로 시작 → 목표 단어 변환  
- 방문 체크로 중복 방지  
- 중복 신고 제거 → Set 사용  
- 신고당한 횟수 count  
- k번 이상 신고된 사람 신고한 유저에게 메일 수 계산  
- 간선 하나씩 끊고 DFS  
- 각 네트워크 노드 수 차이 최소값 계산  
- 끊고 다시 붙이기를 반복
=> [9주차] 이유민 - 알고리즘 중간고사 대비

아빈/9주차/게임맵최단거리.java, 아빈/9주차/괄호회전하기.java, 아빈/9주차/단어변환.java, 아빈/9주차/보물지도.java, 아빈/9주차/신고결과받기.java, 아빈/9주차/전력망을둘로나누기.java
- 게임 맵 최단거리
- Node 클래스를 활용하여 maps 의 각 좌표로 이동할 수 있는지, 이동한 거리를 계산
- 최단거리를 구하는 문제이므로 bfs를 활용
- 괄호회전하기
- 문자열들을 회전하기 위해 deque를 활용
- stack을 활용하여 여는 괄호는 stack에 넣고 닫힌 괄호를 만났을 때 조건에 따라 올바른 괄호를 구하여 해결
- 단어변환
- 단어를 변환하는 최소경로를 찾아야 하기 때문에 bfs를 활용
- canChange 메서드 내에서 다음 index의 문자열로 변환 시 2글자 이상이 차이가 나면 변경이 안되는 문자열로 판별
- 신고 결과 받기
-  Set 과 Map을 활용하여 중복된 신고를 제거하고 신고받은 유저 및 횟수를 저장
-  k번 이상 신고를 받은 유저에 대한 알림 문자를 받은 횟수를 계산하여 반환하여 해결
- 전력망을 둘로 나누기
- 인접리스로 변환 후 dfs를 활용
- 간선을 제거해가면서 최솟값을 구하여 해결
- 보물지도
- 평소 방문기록을 저장하는 visited에 jump에 대한 정보까지 저장해야하기 때문에 3차원 배열로 활용
- bfs를 통해 최소거리를 찾아서 해결
=> [9주차] 조아빈 - 알고리즘 중간고사 대비

하나/10주차/월/멀리 뛰기.java
- dp[i]는 i번째 칸에 도달할 수 있는 방법의 수를 저장하는 배열
- i번째 칸에 오기 위해선 i-1칸에서 1칸, i-2칸에서 2칸 점프하는 두 가지 방법 
- 따라서 점화식은 dp[i] = dp[i-1] + dp[i-2]
- 초기값은 dp[1] = 1, dp[2] = 2로 설정
- 정답은 dp[n
=> [10주차] 김하나 - 월 멀리 뛰기

유민/10주차/월/멀리뛰기.java
- 경우의 수를 저장할 dp 배열 생성  
- 1번째 인덱스에 1 저장, n이 2 이상이면 2번째 인덱스에 2 저장  
- i = 3부터 dp[i] = dp[i - 1] + dp[i - 2] 점화식을 이용해 채움  
- 최종 결과는 dp[n]을 반환
=> [10주차] 이유민 - 월 멀리 뛰기

하나/10주차/수/정수삼각형.java
- 맨 아래 줄부터 위로 올라가며 각 위치에서 만들 수 있는 최대 합을 계산
- triangle[i][j]는 아래의 두 칸 중 큰 값을 선택하여 현재 값에 더함
- triangle[0][0]이 최대합이 됨
=> [10주차] 김하나 - 수 정수 삼각형

재현/10주차/수/정수 삼각형.java
1. 정수 삼각형
- 삼각형 맨 위는 값 그대로 `dp[0][0] = triangle[0][0]` 을 저장
- 칸을 지날때 마다 규칙을 따라서 값을 저장
- 맨 왼쪽 : 위에서 한 칸만 내려옴 `dp[i][0] = dp[i - 1][0] + triangle[i][0]`
- 맨 오른쪽 : 위 오른쪽에서만 내려옴 `dp[i][j] = dp[i - 1][j - 1] + triangle[i][j]`
- 그 외 : 위 두 칸 중 큰 값 선택 `Math.max(dp[i - 1][j - 1], dp[i - 1][j]`
- 최종적으로 구해진 dp에서 마지막 줄의 최댓값을 반환
=> [10주차] 김재현 - 수 정수 삼각형

지은/10주차/수/정수삼각형.java
- 맨 아래에서 위로 올라가며 거꾸로 탐색
- 각 줄의 정수를 순회하며 Math.max로 아래 두 값 중 큰 값을 누적
- 최종적으로 꼭대기 값 `triangle[0][0]`이 전체 경로 중 최대 힙이 됨
=> [10주차] 한지은 - 수 정수삼각형

혁/10주차/수/정수_삼각형.java, 혁/10주차/월/멀리_뛰기.java
- `triangle[i][j]`: 현재 위치
- `triangle[i+1][j]`, `triangle[i+1][j+1]`: 아래 두 자식 노드
- `triangle[i][j] += max(triangle[i+1][j], triangle[i+1][j+1])`
- 아래에서 위로 누적 계산
- 최종적으로 `triangle[0][0]`에 최댓값이 저장됨
=> [10주차] 장혁 - 수 정수 삼각형

유민/10주차/수/정수_삼각형.java
- dp[i][j]에 i행 j열까지의 최대 누적합을 저장  
- 왼쪽 끝은 dp[i][0] = dp[i - 1][0] + triangle[i][0]  
- 오른쪽 끝은 dp[i][i] = dp[i - 1][i - 1] + triangle[i][i]  
- 나머지는 dp[i][j] = max(dp[i - 1][j - 1], dp[i - 1][j]) + triangle[i][j]  
- 마지막 행 중 가장 큰 값을 반환
=> [10주차] 이유민 - 수 정수 삼각형

재현/10주차/금/도둑질.java
1. 도둑질
- 처음 집을 터는 경우와 안터는 경우 두 가지의 경우를 구분
- 처음 집을 터는 경우엔 털 수 있는 집의 인덱스가 0 ~ money.length - 2
- 처음 집을 안터는 경우엔 털 수 있는 집의 인덱스가 1 ~ money.length - 1
- calc 함수를 통해 각각의 경우의 최댓값을 출력 하여 비교
- 최댓값은 `Math.max(dp[i - 1], dp[i - 2] + money[start + i])`를 이용하여 풀이
=> [10주차] 김재현 - 금 도둑질

유민/10주차/금/도둑질.java
- 원형 구조라서 첫 번째 집을 털면 마지막 집은 털 수 없음
- 따라서 아래 두 가지로 나누어서 계산
- dp1: 첫 번째 집을 털고, 마지막 집은 안 털기
- dp2: 첫 번째 집을 안 털고, 마지막 집은 털기 → dp2  
- 각 경우에 대해 점화식 dp[i] = max(dp[i - 1], dp[i - 2] + money[i]) 를 사용  
- 두 경우의 최댓값 중 더 큰 값을 정답으로 선택하여 반환
=> [10주차] 이유민 - 금 도둑질

지은/10주차/금/도둑질.java
- 원형 구조로 인해 첫 집을 털면 마지막 집은 못 털고, 첫 집을 안 털면 마지막 집은 털 수 있음
- 두 경우를 나눠 각각 DP로 계산
- dp1: 첫 집 포함, 마지막 집 제외
- dp2: 첫 집 제외, 마지막 집 포함
- 두 결과 중 큰 값을 반환
=> [10주차] 한지은 - 금 도둑질

하나/10주차/금/도둑질.java
- 집이 원형으로 연결되어 있기 때문에 두 가지 경우로 나눈다
- 첫 번째 집을 털고, 마지막 집은 안 턴다, 첫 번째 집을 안 털고, 마지막 집을 턴다
- 1번의 경우 0번째 집부터 (n-2)번째 집까지 탐색
- 2번의 경우 1번째 집부터 (n-1)번째 집까지 탐색
=> [10주차] 김하나 - 금 도둑질

재현/11주차/월/등굣길.java
1. 등굣길
- inWater라는 함수를 이용하여 현재 좌표가 물에 잠겼는지 안잠겼는지 true / false 반환
- dp 배열을 만들어 초기값 (출발지) 을 1로 설정
- for문을 돌며 현재 위치의 케이스에 따라 계산
- `i == 1 && j == 1` : 출발지일 경우 continue
- `inWater(i, j, puddles) == true` :  물에 잠긴 좌표일 경우 0으로 설정
- `inWater(i, j, puddles) == false` : 이동 방향이 아래와 오른쪽이므로 현재 좌표의 위, 왼쪽 좌표의 합을 구한 뒤 1000000007로 나눈 나머지 저장
- 최종적으로 n, m 좌표 값 dp[n][m]을 반환
=> [11주차] 김재현 - 월 등굣길

지은/11주차/등굣길.java
- street[i][j]는 (0,0)부터 (i,j)까지 갈 수 있는 경로 수를 저장하는 DP 테이블로 정의
- 웅덩이는 -1로 표시한 뒤 탐색 시 0으로 초기화하여 경로 계산에서 제외
- 각 칸에 대해 위쪽(i-1)과 왼쪽(j-1)에서 오는 경로 수를 더해 현재 칸에 누적
- 결과값은 MOD(1,000,000,007)를 사용해 나머지 연산 처리하며, 최종 목적지 경로 수를 반환함
=> [11주차] 한지은 - 월 등굣길

경조/11주차/월/등굣길.java
- 문제의 좌표는 `(m, n)`이지만 `(열, 행)` 방식으로 준 것이므로 `(n, m)`으로 변경해주었습니다.
- 2차원 배열인 dp를 선언했습니다.
- `dp[i][j] = (i, j)` 위치까지 도달할 수 있는 경로의 수
- `(i, j)`에 올 수 있는 경로는 위쪽(`dp[i-1][j]`)과 왼쪽(`dp[i][j-1]`)에서 오는 경로 뿐입니다.
=> [11주차] 정경조 - 월 등굣길

유민/11주차/월/등굣길.java
- (1,1)에서 시작해 오른쪽 또는 아래로만 이동하며 (m,n)까지 가는 경로 수를 구함  
- 물웅덩이는 도달 불가능하므로 해당 위치의 dp[i][j]는 0으로 처리  
- dp[i][j] = dp[i-1][j] + dp[i][j-1] 식을 이용해 경로 수 계산  
- 처음엔 (0,0)부터 시작해서 인덱스 오류가 났으나, (1,1)부터 시작하도록 수정했더니 해결됐다!
=> [11주차] 이유민 - 월 등굣길

혁/10주차/금/도둑질.java
**원형 구조** → 일반 선형 도둑질 문제로 나누어 해결
1. 첫 번째 집을 털고 마지막 집은 못 터는 경우  
→ `arr[0] ~ arr[n-2]` 구간에서 최대값 계산
2. 첫 번째 집을 안 털고 마지막 집을 터는 경우  
→ `arr[1] ~ arr[n-1]` 구간에서 최대값 계산
→ 두 경우 중 더 큰 값을 선택
=> [10주차] 장혁 - 금 도둑질

하나/11주차/월/등굣길.java
1. DP 정의
- dp[y][x]: (1,1)부터 (x+1, y+1)까지 올 수 있는 경로의 수
* 초기값: dp[0][0] = 1
2. 점화식
- dp[y][x] = dp[y-1][x] + dp[y][x-1]
- 위쪽에서 오는 경로 수 + 왼쪽에서 오는 경로 수
* dp[y][x]가 물웅덩이라면 0으로 처리
3. 물웅덩이 처리
- puddles 좌표는 (x, y)로 주어지며, 배열 인덱스에서는 [y-1][x-1]로 변환
- 해당 위치를 -1로 마킹 후, DP 계산 시 0으로 바꿔 무시
=> [11주차] 김하나 - 월 등굣길

재현/11주차/수/사칙연산.java
1. 사칙연산
- 연산자와 피연산자를 구분하여 저장하기 위해 nums와 ops 배열을 생성하여 저장
- 최댓값과 최솟값을 저장하기 위한 dpMax와 dpMin 배열을 생성 후 dpMax[i][i], dpMin[i][i]는 nums[i]로 초기화
- 구간 길이를 1 ~ n  - 1까지 늘려가며 모든 구간 계산
- 각 구간을 [i][j]를 연산자 위치 k를 기준으로 좌우로 나눠서 계산
- 왼쪽: dpMax[i][k], dpMin[i][k]
- 오른쪽: dpMax[k + 1][j], dpMin[k + 1][j]
- 덧셈일 경우 최댓값은 최대 + 최대, 최솟값은 최소 + 최소
- 뺼셈일 경우 최댓값은 최대 - 최소, 최솟값은 최소 - 최대
- 이후 최종으로 구해진 결과에서 dpMax[0][n - 1]을 통해 최댓값을 반환
=> [11주차] 김재현 - 수 사칙연산

재현/11주차/금/N으로 표현.java
1. N으로 표현
- N번 사용된 숫자들의 집합 Set을 저장할 dp를 List로 선언
- `Ìnteger.parseInt(String.valueOf(N).repeat(i))` 함수를 이용하여 N이 i번 사용된 숫자를 생성
- i번 사용된 숫자를 구하면 i보다 작은 횟수를 사용한 숫자들의 set을 이용하여 i번 사용된 숫자들의 사칙연산들의 결과를 계산
- i번 사용된 숫자의 사칙연산이 끝난 후 만약 number가 존재하면 i를 반환
- 아닌 경우 dp 저장한 다음 i + 1번째 연산 시작 후 마지막까지 없으면 -1를 반환
=> [11주차] 김재현 - 금 N으로 표현

경조/11주차/금/N으로표현.java
- `N`을 몇 개를 사용하면 `number`가 나올 수 있는지 찾는 문제입니다. (`8개 이상은 -1 리턴`)
- `ArrayList`를 이용하여 숫자를 사용한 개수마다 연산 결과를 `HashSet`에 추가해줬습니다.
- 반복문을 통해 8개를 사용하는 경우까지 반복하며 `HashSet`에 `number`가 있으면 해당 개수를 리턴
- 없다면 `-1`을 리턴하도록 했습니다.
=> [11주차] 정경조 - 금 N으로 표현

지은/11주차/N으로 표현.java
- N 을 몇 번 사용해야 number를 만들 수 있는지 찾는 문제
- N을 i번 사용해서 만들 수 있는 수들을 HashSet으로 저장
- 사칙연산 + 숫자 이어붙이기로 만들 수 있는 수를 dp에 저장
- 숫자 이어붙이기는 별도 메서드 makeRepeatedNumber로 처리
- 8번 안에 만들 수 있으면 i 반환, 못 만들면 -1 리턴
=> [11주차] 한지은 - 금 N으로 표현

유민/11주차/금/N으로_표현.java
- 숫자 N을 1개부터 8개까지 사용하여 target 숫자를 만들 수 있는 최소 횟수를 구함  
- 같은 숫자를 반복해서 사용하는 경우를 포함하기 위해 N을 i번 이어붙인 수도 직접 추가  
- 사칙연산으로 조합 가능한 모든 숫자들을 Set에 저장하며, 중복을 제거하고 최적화  
- dp[i] = dp[j] (연산자) dp[i-j] (j는 1부터 i-1까지) 로 구성된 모든 사칙연산 결과를 누적  
- 중간에 target 숫자가 만들어지면 해당 i를 정답으로 리턴하고 종료  
- 8개까지 모두 탐색해도 못 만들면 -1 리턴
=> [11주차] 이유민 - 금 N으로 표현

하나/11주차/금/N으로 표현.java
- dp[i]는 N을 i번 사용해서 만들 수 있는 모든 숫자들을 저장하는 set
- dp[1]에는 N을 1번 써서 만들 수 있는 숫자들 저장
- dp[2]에는 N을 2번 써서 만들 수 있는 숫자들 저장
- 각 단계(i)마다 dp[i] 안에 number가 들어있으면, 그때의 i가 최소 사용 횟수 -> 찾으면 바로 return
=> [11주차] 김하나 - 금 N으로 표현

지은/12주차/월/합승택시요금.java
- 출발지 s에서 두 사람이 택시를 타고 가다가 중간에 갈라져 a, b 각자 목적지로 가는 최소 요금을 구하는 문제(합승하든 안하든 상관없음)
- 그래프는 인접 리스트로 구성하고, s, a, b를 각각 시작점으로 다익스트라 3번 실행해서 모든 노드까지의 최소 요금을 계산
- distS[k], distA[k], distB[k]는 각각 s→k, k→a, k→b까지의 최소 요금
- 각 노드를 경유지 k로 가정하고, 세 경로의 요금 합(distS[k] + distA[k] + distB[k])을 계산하고, 그 중 최소값을 선택해서 리턴
=> [12주차] 한지은 - 월 합승 택시 요금

유민/12주차/월/합승택시요금.java
- 모든 지점 간 최단 거리 구하기 위해 플로이드-워셜 알고리즘 사용
- 합승 후 갈라질 수 있는 경유지점(k)을 1~n까지 모두 시도하여 최소 비용 계산
- 최소 비용 = s→k + k→a + k→b
- 초기값을 0으로 설정했다가 의도치 않게 최소값이 덮여버려 오답 발생해서 INF로 초기화해 해결했습니다!
=> [12주차] 이유민 - 월 합승 택시 요금

경조/12주차/월/합승택시요금.java
- 특정 출발점 `s`에서 출발해 두 사람의 각 목적지 `a`, `b`로 가는 최소 비용을 계산하는 문제입니다.
- 중간까지는 합승이 가능하며, 그 이후 각자 목적지로 이동합니다.
- `s`, `a`, `b`에서 각각 다익스트라 알고리즘을 수행하여 최소 비용 배열을 구합니다.
- 모든 노드를 `i`를 경유지로 가정하고, `s -> i`, `a -> i`, `b -> i`를 더한 값 중 최소값을 구합니다.
- 다익스트라 함수에서 최소 비용 경로 계산을 위해 우선순위큐를 사용했습니다.
- Edge 클래스에 `Comparable` 구현하여 우선순위큐에서 비용 기준 정렬했습니다.
=> [12주차] 정경조 - 월 합승 택시 요금

경조/12주차/수/경주로_건설.java, 경조/12주차/수/단속카메라.java
- 먼저 도착 지점 순으로 정렬을 해줍니다.
- 카메라가 진입 시점보다 앞에 있으면(작으면) 단속이 되지 않습니다.
- 카메라가 단속하지 못 했다면 해당 차량의 진출 시점에 카메라를 설치하고 `answer` 값을 증가합니다.
---
- 최단 비용 문제이므로 bfs를 이용하여 풀었습니다.
- 현재 위치, 비용, 방향을 저장할 `Move` 클래스를 선언해주었습니다.
- 상하좌우 접근 방향에 따라 비용이 달라지므로 `visited` 배열을 3차원 배열로 선언해주었습니다.
- `dir` 방향이 현재 방향과 방문할 방향이 같다면 `nextCost += 100` 아니라면 `nextCost += 600`을 해주었습니다.
- 최종적으로 `visited` 배열에서 최종 목적지의 방향별 비용에서 최소 비용을 리턴해줍니다.
=> [12주차] 정경조 - 수 단속카메라, 경주로 건설

혁/12주차/수/경주로_건설.java, 혁/12주차/수/단속카메라.java
모든 차량이 단속 카메라를 한 번은 만나도록 최소한의 카메라를 설치해야 함
- 각 차량은 [진입 시점, 진출 시점]으로 주어짐
- 진입/진출 시점에 설치해도 감지됨
- 차량의 경로가 겹치는 곳에 카메라를 설치하면 여러 대를 동시에 단속 가능
1. 차량 경로를 **진출 지점 기준 오름차순** 정렬
2. **가장 먼저 나가는 차량의 진출 지점에 카메라** 설치
3. 그 카메라에 잡히지 않는 차량에 대해 반복
0과 1로 구성된 격자에서, (0,0) → (N-1,N-1)로 가는 최소 비용 경로를 찾아야 함
- 직선 도로: 100원
- 방향이 꺾이면(코너): 추가로 500원 발생
- 최단 경로지만 코너를 줄이는 전략이 필요
1. BFS로 `(x, y, 비용, 방향)`을 상태로 하여 탐색
2. 같은 칸이라도 **방향에 따라 최소비용이 달라질 수 있음**
3. 방향이 바뀔 경우 코너 비용을 더함
4. 모든 방향에 대해 도착점에서 최소 비용을 선택
=> [12주차] 장혁 - 수 경주로 건설, 단속카메라

하나/12주차/금/자물쇠와열쇠.java
1. key가 lock 영역을 벗어나서도 움직일 수 있다 -> lock를 확장해서 중앙에 놓는다.
2. key는 90도씩 회전할 수 있으므로 최대 4번 회전하면서 확인
3. key 배열을 lock 위에 덧셈으로 합쳐보고
4. lock 중앙 부분이 모두 1이면 성공
5. 아니면 복원하고 반복 -> 끝까지 안되면 false
=> [12주차] 김하나 - 금 자물쇠와 열쇠

경조/12주차/금/자물쇠와열쇠.java
- 열쇠가 자물쇠 시작과 끝 경계에서 겹치는 모든 경우를 탐색하게 합니다.
- `offset`은 자물쇠가 `board` 내에서 시작될 위치입니다.
- `key`를 `rotated90`를 이용하여 네 방향(0, 90, 180, 270)으로 회전하여 `rotatedKeys`에 저장해줬습니다.
- `applyKey`를 통해 `board` 배열에 `key` 값을 더 해줍니다.
- `check`를 통해 `lock` 부분이 모두 `1`인지 확인합니다.
- `1`이라면 자물쇠와 열쇠가 맞았다는 것이고 아니라면 안 맞았다는 것입니다.
=> [12주차] 정경조 - 금 자물쇠와 열쇠

지은/12주차/금/자물쇠와 열쇠.java
- 2차원 배열 key와 lock은 홈(0), 돌기(1) 로 주어지고, key를 회전하거나 이동시켜 lock을 열 수 있는지 판단하는 문제
- lock의 모든 홈(0)이 key의 돌기(1)로 정확히 채워지고 겹치는 돌기가 없어야 함.
- key를 90도 회전 4번시키며 lock위 모든 위치에 덮어보는 완전 탐색 사용
- key는 lock 바깥으로도 이동할 수 있으므로 lock을 3배 크기 배열 중앙에 배치
- key를 덮을 때마다 값을 더하고 -> 중앙 lock 영역이 모두 1인지 검사 -> 아니면 키를 복구하며 다음 위치로 이동 반복
- 어떤 경우에도 열리지 않으면 false, 열리면 true 리턴
=> [12주차] 한지은 - 금 자물쇠와 열쇠

아빈/12주차/금/자물쇠와열쇠.java
- 자물쇠와 열쇠
- 해당 문제는 주어진 조건에 맞게 key를 회전, 이동 시켜 lock을 열 수 있는지 판별하여 반환하는 문제였습니다.
- 키가 돌 며 판별할 수 있도록 lock을 확장시켜주었습니다.
- rotate 를 통해 key를 회전시킨 후 check 를 통해 현재 key가 lock 을 열 수 있는지 판별하도록 하였습니다.
- 만약 check를 통과 하지 않는다면 이전에 key 를 덮었던 lock을 원상복구 시켜준 후 반복문을 돌며 key를 다음 위치로 이동시키며 문제를 해결할 수 있었습니다.
=> [12주차] 조아빈 - 금 자물쇠와 열쇠

유민/12주차/금/자물쇠와_열쇠.java
- 자물쇠를 3배 크기의 보드 중앙에 배치하고, 키를 이동 및 회전시키며 맞춰봄
- 키를 보드에 더하고 다시 빼는 방식으로 시도 → 중간에 맞는 순간 true 반환
- 정답 조건 확인은 자물쇠 영역(board[N~2N][N~2N])이 모두 1인지 확인
=> [12주차] 이유민 - 금 자물쇠와 열쇠

재현/13주차/월/방문 길이.java, 재현/13주차/월/숫자 게임.java
1. 숫자 게임
- 처음에는 dfs를 이용하여 풀이를 하였으나 시간초과로 풀이 실패
- 그리디 알고리즘을 이용하여 문제 풀이
- A와 B를 우선 정렬
- 가장 많은 승리를 하는 경우에는 B가 A 숫자보다 큰 수들 중에서 가장 작은 수를 내는게 가장 최고의 선택
- 포인터 두개를 이용하여 B가 이길 수 있으면 count++ 이후 A와 B 모두 인덳 ㅡ증가
- B가 못 이기면 B는 다음 숫자를 시도
- 최종 count 값 반환
2. 방문 길이
- 이동 방향과 dirStr를 미리 선언하여 인덱스만 이용해서 이동을 가능하게 함
- 3차원 배열을 이용하여 방문을 하였는지 안하였는지 확인하고 이동 방향까지 작성
- 만약 처음 이동하는 경로이면 count++를 한 뒤 이동 경로 방향에 대해서 true로 반대 방향으로 이동하는 경우도 true로 표기
- 최종 count 값 반환
=> [13주차] 김재현 - 월 숫자게임, 방문 길이

아빈/13주차/월/방문길이.java, 아빈/13주차/월/숫자게임.java
- 숫자 게임
- 해당 문제는 주어진 A와 B의 숫자들을 비교하여 B가 이길 수 있는 최대의 경우의 수를 출력하는 문제였습니다.
- A와 B를 오름차순 정렬 후 조건에 따라 두 수를 비교 후 문제를 해결할 수 있었습니다.
- 방문 길이
- 해당 문제는 0,0에서 시작하여 주어진 명령어대로 이동 시 같은 길을 사용하지 않은 길의 개수를 출력하는 문제였습니다.
- 방문한 길의 중복을 체크하기 위해 visited를 set으로 선언하였습니다.
- 명령어 대로 이동한 다음좌표와 현재 좌표를 문자열로 만들어 만약 visited에 이미 있는 경로가 아니라면 answer을 1씩 증가하여 문제를 해결할 수 있었습니다.
=> [13주차] 조아빈 - 월 숫자게임, 방문길이

하나/13주차/월/방문길이.java, 하나/13주차/월/숫자게임.java
1. 숫자 게임
- A와 B를 오름차순으로 정렬
- B 기준으로 순회하면서
- A가 큰 경우는 넘기고, B가 큰 경우만 카운트
2. 방문 길이
- (0,0)에서 시작해 명령어에 따라 이동
- 이동할 때 경계 밖으로 나가면 continue
- 이동한 길(출발→도착, 도착→출발)을 Set 에 저장해 중복을 제거
- Set 에 저장된 길의 수 / 2 가 처음 지나간 길의 수가 됨
=> [13주차] 김하나 - 월 숫자 게임, 방문 길이

재현/13주차/수/광물 캐기.java, 재현/13주차/수/택배상자.java
1. 광물캐기
- 하나의 곡괭이는 5개를 캐야하기에 광물을 5개씩 묶어 그룹화 하고 각 그룹의 피로도 가중치를 계산하여 정렬
- 다이아 곡괭이부터 순서대로 각 그룹에 사용하여 피로도를 누적
- 곡괭이 수만큼 그룹을 처리하고 더 이상 없으면 종료
- 최종 누적된 피로도를 반환
2. 택배상자
- 컨베이어 벨트가 한쪽으로만 나가고 들어가기에 stack 자료구조를 이용
- 컨베이어 벨트에서 1번부터 순서대로 상자를 꺼냄
- 필요한 상자면 가져가고 아니면 스택에 넣음
- 스택 top이 다음 상자면 꺼내서 가져감
- 최종 가져간 상자의 수를 반환
=> [13주차] 김재현 - 수 광물캐기, 택배상자

하나/13주차/수/광물 캐기.java, 하나/13주차/수/택배상자.java
1. 택배 상자
- 컨테이너 벨트에서 오는 상자를 1번부터 순서대로 처리, 트럭에 실을 수 있으면 실어준다.
- 실을 수 없으면 보조 스택에 넣고, 스택 맨 위가 현재 실어야 하는 상자와 같으면 꺼내서 실어준다.
- 벨트와 보조 스택을 번갈아가며 트럭에 실을 수 있을 때까지 반복한다.
- 트럭에 실은 상자 개수를 반환한다.
2. 광물 캐기
- 광물을 5개씩 그룹으로 나눈다
- 각 그룹 피로도 계산 후, 블록 index랑 같이 저장한다
- 피로도 높은 그룹부터(가장 힘든 구간) 좋은 곡괭이 배정한닫
- 곡괭이 없거나 광물 끝날 때까지 최소 피로도 계산 후 리턴한다
=> [13주차] 김하나 - 수 택배 상자, 광물 캐기

경조/13주차/수/광물캐기.java, 경조/13주차/수/택배상자.java
- `order` 배열에 트럭에 들어가야할 박스 번호의 순서가 주어집니다.
- 보조 컨테이너 벨트를 스택으로 구현했습니다.
- 1부터 5까지 반복문에서 먼저 스택에 넣은 후 마지막에 넣은 값이 `order[idx]`와 같다면 `pop`, `idx++`를 해주면서 정답도 증가 시켜줍니다.
- `picks`에 각 곡괭이의 수가 주어집니다.
- 곡괭이는 피로도와 관계없이 5개의 광물을 캐면 파괴되므로 광물을 5개씩 묶어서 계산했습니다.
- `Mineral` 클래스를 선언하여 다이아, 철, 돌을 저장해주었습니다.
- `Mineral` 클래스에 피로도를 계산할 수 있는 `score` 함수도 선언해주었습니다.
- 피로도는 돌 곡괭이 기준으로 계산하여 다이아가 많은 순으로 정렬할 수 있게 하였습니다.
- `ArrayList`에 5개씩 광물의 수를 계산한 `Mineral` 클래스를 저장하고 피로도가 높은 순으로 정렬했습니다.
=> [13주차] 정경조 - 수 택배 상자, 광물 캐기

아빈/13주차/수/광물캐기.java, 아빈/13주차/수/택배상자.java
- 택배 상자
- 해당 문제는 1~5까지 순서대로 들어오는 상자를 택배 기사의 주어진 order대로 배달할 수 있는 상자의 개수를 출력하는 문제였습니다.
- 보조 컨테이너에는 가장 나중에 들어간 상자가 가장 빨리 나올 수 있다는 점을 고려하여 스택을 활용하였습니다.
- 조건에 맞게 반복문을 돌며 배달 가능한 상자의 개수를 구할 수 있었습니다.
- 광물 캐기
- 해당 문제는 곡괭이 종류와, 캐야하는 광물 종류에 따라 곡괭이를 다 쓰거나 광물을 캘 때 가장 적게 소모하는 피로도를 구하는 문제였습니다.
- 한 곡괭이로 5개의 광물을 캘 수 있으므로 5개씩 묶은 리스트를 만들어주었습니다.
- 만들어진 묶음 리스트에서 좋은 곡괭이로 강도가 강한 광물을 캐는 것이 유리하다는 전제로 정렬을 해주었습니다.
- 다음 반복문에서 해당 광물을 캘 때 드는 피로도를 계산하여 해결할 수 있었습니다.
=> [13주차] 조아빈 - 수 택배상자, 광물캐기

혁/11주차/금/N으로_표현.java, 혁/12주차/금/자물쇠와_열쇠.java, 혁/13주차/수/광물_캐기.java, 혁/13주차/수/택배상자.java
1. `Stack<Integer> subBelt = new Stack<>();`
- 보조 컨테이너 벨트 역할을 하는 스택 선언.
2. `int box = 1;`
- 컨베이어 벨트에서 나오는 상자 번호 (1번부터 시작).
3. `int index = 0;`
- 택배 기사님이 알려준 순서 배열 `order`의 인덱스.
4. `while (box <= order.length)`
- 모든 상자를 순차적으로 확인할 때까지 반복.
5. `if (order[index] == box)`
- 현재 컨베이어 벨트에서 나오는 상자가 실어야 할 상자와 같다면:
- 상자를 트럭에 실고 `index`, `box`를 증가시킴.
6. `else if (!subBelt.isEmpty() && subBelt.peek() == order[index])`
- 보조 컨테이너 벨트의 맨 위 상자가 지금 실어야 할 상자라면:
- 보조 벨트에서 꺼내서 트럭에 실음, `index` 증가.
7. `else`
- 지금 실어야 할 상자가 아니므로:
- 현재 상자를 보조 컨테이너 벨트에 넣음, `box` 증가.
8. `while (!subBelt.isEmpty() && subBelt.peek() == order[index])`
- 남아있는 보조 벨트에서도 순서에 맞는 상자를 실을 수 있는지 반복.
9. `return index;`
- 실을 수 있었던 상자의 개수를 반환.
---
1. `int fatigue = 0;`
- 누적 피로도 총합을 저장하는 변수.
2. `List<int[]> chunks = new ArrayList<>();`
- 광물을 5개씩 묶은 …
=> [13주차] 장혁 - 수 택배상자, 광물 캐기

아빈/13주차/금/주차요금계산.java
- 주차 요금 계산
- 해당 문제는 주어진 요금 표 `fees`와 입출차 기록 배열인 `records`를 활용하여 조건에 맞게 주차 요금을 차 번호 순으로 출력하는 문제였습니다.
- 입차 정보를 관리할 inRecordMap과 총 주차 시간을 누적하며 저장시킬 totalMap을 활용하였습니다.
- 이때 번호 순으로 정렬하기 위해 TreeMap으로 선언해주었습니다.
- totalMap에 저장한 차량별 누적시간과 `fees`를 활용하여 주차 요금을 계산 후 출력시켜 해결하였습니다.
=> [13주차] 조아빈 - 금 주차 요금 계산

재현/13주차/금/주차 요금 계산.java
1. 주차 요금 계산
- Time 클래스를 선언하여 시간 관리
- `Map<Integer, List<Time>> map`을 통해 차 번호마다 자동차 번호와 시간을 저장
- 만약 map에서 리스트 크기가 홀수이면 출차를 하지 않은것이므로 Time(23, 59)를 추가
- `Map<Integer, Integer> timeMap`을 통해 차 번호마다 누적 시간을 저장
- `List<int[]> feeList` 리스트에 자동차 번호와 시간을 통해 주차 요금을 계산하여 리스트로 저장
- 이후 자동차 번호 순으로 정렬을 하여 answer 배열에 넣고 반환
=> [13주차] 김재현 - 금 주차 요금 계산
